import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';

/// List of categories of emojis
const List<CategoryEmoji> defaultEmojiSet = [
// ======================================================= Category.SMILEYS
  CategoryEmoji(Category.SMILEYS, [
    Emoji('😀', 'にこにこ'),
    Emoji('😃', '目が大きく笑っている顔'),
    Emoji('😄', '笑顔で笑っている顔'),
    Emoji('😁', '笑っている顔'),
    Emoji('😆', '顔をしかめて笑う'),
    Emoji('😅', '冷や汗をかきながら笑う顔'),
    Emoji('🤣', '笑い転げる'),
    Emoji('😂', '大笑い'),
    Emoji('🙂', 'わずかに笑っている顔'),
    Emoji('🙃', '逆さまの顔'),
    Emoji('😉', 'ウィンクする顔'),
    Emoji('😊', 'にっこり'),
    Emoji('😇', '天使の笑顔'),
    Emoji('🥰', 'ハートで笑っている顔'),
    Emoji('😍', 'ハート目で笑っている顔'),
    Emoji('🤩', 'スターのような目'),
    Emoji('😘', '投げキッスをする顔'),
    Emoji('😗', 'キスをする顔'),
    Emoji('☺️', '微笑む'),
    Emoji('😚', '目を閉じてキスをする顔'),
    Emoji('😙', '笑顔でキスをする顔'),
    Emoji('😋', 'おいしそうに食べる顔'),
    Emoji('😛', '舌を出す顔'),
    Emoji('😜', '舌を出してウィンクする顔'),
    Emoji('🤪', '変な顔'),
    Emoji('😝', '舌を出して目を細める顔'),
    Emoji('🤑', 'お金の口の顔'),
    Emoji('🤗', 'ハグする顔'),
    Emoji('🫣', '覗き見する顔'),
    Emoji('🤭', '口を手で覆う顔'),
    Emoji('🫢', '目を開けて口を手で覆う顔'),
    Emoji('🫡', '敬礼する顔'),
    Emoji('🤫', '静かにする顔'),
    Emoji('🫠', '溶ける顔'),
    Emoji('🤔', '考える顔'),
    Emoji('🤐', '口にチャックをする顔'),
    Emoji('🤨', '眉を上げた顔'),
    Emoji('😐', '無表情な顔'),
    Emoji('🫤', '斜めの口の顔'),
    Emoji('😑', '無表情'),
    Emoji('😶', '口のない顔'),
    Emoji('🫥', '点線の顔'),
    Emoji('😏', 'ニヤニヤする顔'),
    Emoji('😒', '面白くない顔'),
    Emoji('🙄', '目を回す顔'),
    Emoji('😬', 'しかめっ面'),
    Emoji('🤥', '嘘をつく顔'),
    Emoji('😌', '安心した顔'),
    Emoji('😔', '物思いにふける顔'),
    Emoji('🥹', '涙をこらえる顔'),
    Emoji('😪', '眠そうな顔'),
    Emoji('🤤', 'よだれを垂らす顔'),
    Emoji('😴', '眠っている顔'),
    Emoji('😷', 'マスクをした顔'),
    Emoji('🤒', '体温計のある顔'),
    Emoji('🤕', '頭に包帯を巻いた顔'),
    Emoji('🤢', '吐き気がする顔'),
    Emoji('🤮', '嘔吐する顔'),
    Emoji('🤧', 'くしゃみをする顔'),
    Emoji('🥵', '熱い顔'),
    Emoji('🥶', '寒い顔'),
    Emoji('🥴', 'ふらふらする顔'),
    Emoji('😵', '目が回る顔'),
    Emoji('🤯', '頭が爆発する'),
    Emoji('🤠', 'カウボーイハットの顔'),
    Emoji('🥳', 'パーティーをしている顔'),
    Emoji('😎', 'サングラスをかけた笑顔'),
    Emoji('🤓', 'オタクの顔'),
    Emoji('🧐', '片眼鏡の顔'),
    Emoji('😕', '困惑した顔'),
    Emoji('😟', '心配そうな顔'),
    Emoji('🙁', '少ししかめっ面'),
    Emoji('☹️', 'しかめっ面'),
    Emoji('😮', '口を開けた顔'),
    Emoji('😯', '静かな顔'),
    Emoji('😲', '驚いた顔'),
    Emoji('😳', '赤面した顔'),
    Emoji('🥺', '懇願する顔'),
    Emoji('😦', '口を開けてしかめっ面'),
    Emoji('😧', '苦悩の顔'),
    Emoji('😨', '恐ろしい顔'),
    Emoji('😰', '冷や汗をかいて不安そうな顔'),
    Emoji('😥', '悲しんでいるが安心した顔'),
    Emoji('😢', '泣いている顔'),
    Emoji('😭', '大声で泣いている顔'),
    Emoji('😱', '恐怖で叫ぶ顔'),
    Emoji('😖', '困惑した顔'),
    Emoji('😣', '頑張る顔'),
    Emoji('😞', 'がっかりした顔'),
    Emoji('😓', '冷や汗をかいてがっかりした顔'),
    Emoji('😩', '疲れた顔'),
    Emoji('😫', '疲れた顔'),
    Emoji('😤', '鼻から蒸気が出ている顔'),
    Emoji('😡', 'ふくれっ面'),
    Emoji('😠', '怒っている顔'),
    Emoji('🤬', '口に記号のある顔'),
    Emoji('😈', '角のある笑顔'),
    Emoji('👿', '角のある怒った顔'),
    Emoji('💀', 'ドクロ'),
    Emoji('☠️', 'ドクロと交差した骨'),
    Emoji('💩', 'うんち'),
    Emoji('🤡', 'ピエロの顔'),
    Emoji('👹', '鬼'),
    Emoji('👺', '天狗'),
    Emoji('👻', '幽霊'),
    Emoji('👽', '宇宙人'),
    Emoji('👾', 'エイリアンモンスター'),
    Emoji('🤖', 'ロボットの顔'),
    Emoji('🎃', 'ジャック・オー・ランタン'),
    Emoji('😺', 'にやりと笑う猫の顔'),
    Emoji('😸', '笑顔で笑っている猫の顔'),
    Emoji('😹', '喜びの涙を流す猫の顔'),
    Emoji('😻', 'ハート目で笑っている猫の顔'),
    Emoji('😼', '皮肉な笑みを浮かべる猫の顔'),
    Emoji('😽', 'キスをする猫の顔'),
    Emoji('🙀', '疲れた猫の顔'),
    Emoji('😿', '泣いている猫の顔'),
    Emoji('😾', 'ふくれっ面の猫の顔'),
    Emoji('🫶', 'ハートの手', hasSkinTone: true),
    Emoji('👋', '手を振る', hasSkinTone: true),
    Emoji('🤚', '手の甲を上げる', hasSkinTone: true),
    Emoji('🖐️', '指を広げた手', hasSkinTone: true),
    Emoji('✋', '上げた手', hasSkinTone: true),
    Emoji('🖖', 'バルカン式敬礼', hasSkinTone: true),
    Emoji('👌', 'OKサイン', hasSkinTone: true),
    Emoji('🤌', 'ピンチした指', hasSkinTone: true),
    Emoji('🤏', 'つまむ手', hasSkinTone: true),
    Emoji('🫳', '手のひらを下に向けた手', hasSkinTone: true),
    Emoji('🫴', '手のひらを上に向けた手', hasSkinTone: true),
    Emoji('✌️', 'ピースサイン', hasSkinTone: true),
    Emoji('🫰', '人差し指と親指を交差させた手', hasSkinTone: true),
    Emoji('🤞', '指を交差させる', hasSkinTone: true),
    Emoji('🤟', '愛してるサイン', hasSkinTone: true),
    Emoji('🤘', 'ロックンロールサイン', hasSkinTone: true),
    Emoji('🤙', '電話してサイン', hasSkinTone: true),
    Emoji('👈', '左を指す', hasSkinTone: true),
    Emoji('👉', '右を指す', hasSkinTone: true),
    Emoji('👆', '上を指す', hasSkinTone: true),
    Emoji('🖕', '中指を立てる', hasSkinTone: true),
    Emoji('👇', '下を指す', hasSkinTone: true),
    Emoji('☝️', '上を指差す', hasSkinTone: true),
    Emoji('👍', 'いいね！', hasSkinTone: true),
    Emoji('👎', 'よくないね', hasSkinTone: true),
    Emoji('✊', '拳を上げる', hasSkinTone: true),
    Emoji('👊', '握りこぶし', hasSkinTone: true),
    Emoji('🤛', '左向きの握りこぶし', hasSkinTone: true),
    Emoji('🤜', '右向きの握りこぶし', hasSkinTone: true),
    Emoji('🫲', '左向きの手', hasSkinTone: true),
    Emoji('🫱', '右向きの手', hasSkinTone: true),
    Emoji('👏', '拍手する', hasSkinTone: true),
    Emoji('🙌', '両手を上げる', hasSkinTone: true),
    Emoji('👐', '両手を開く', hasSkinTone: true),
    Emoji('🤲', '手のひらを合わせる', hasSkinTone: true),
    Emoji('🤝', '握手', hasSkinTone: true),
    Emoji('🙏', '合掌', hasSkinTone: true),
    Emoji('🫵', '指差す', hasSkinTone: true),
    Emoji('✍️', '書く手', hasSkinTone: true),
    Emoji('💅', 'ネイルポリッシュ', hasSkinTone: true),
    Emoji('🤳', '自撮り', hasSkinTone: true),
    Emoji('💪', '力こぶ', hasSkinTone: true),
    Emoji('🦵', '脚', hasSkinTone: true),
    Emoji('🦶', '足', hasSkinTone: true),
    Emoji('👂', '耳', hasSkinTone: true),
    Emoji('👃', '鼻', hasSkinTone: true),
    Emoji('🧠', '脳'),
    Emoji('🦴', '骨'),
    Emoji('👀', '目'),
    Emoji('👁️', '目'),
    Emoji('💋', 'キスマーク'),
    Emoji('👄', '口'),
    Emoji('🫦', '唇を噛む'),
    Emoji('🦷', '歯'),
    Emoji('👅', '舌'),
    Emoji('👶', '赤ちゃん', hasSkinTone: true),
    Emoji('🧒', '子供', hasSkinTone: true),
    Emoji('👦', '男の子', hasSkinTone: true),
    Emoji('👧', '女の子', hasSkinTone: true),
    Emoji('🧑', '人', hasSkinTone: true),
    Emoji('👨', '男性', hasSkinTone: true),
    Emoji('🧔', 'ひげを生やした男性', hasSkinTone: true),
    Emoji('👱', 'ブロンドの男性', hasSkinTone: true),
    Emoji('👨‍🦰', '赤毛の男性', hasSkinTone: true),
    Emoji('👨‍🦱', '巻き毛の男性', hasSkinTone: true),
    Emoji('👨‍🦳', '白髪の男性', hasSkinTone: true),
    Emoji('👨‍🦲', 'はげ頭の男性', hasSkinTone: true),
    Emoji('👩', '女性', hasSkinTone: true),
    Emoji('👱‍♀️', 'ブロンドの女性', hasSkinTone: true),
    Emoji('👩‍🦰', '赤毛の女性', hasSkinTone: true),
    Emoji('👩‍🦱', '巻き毛の女性', hasSkinTone: true),
    Emoji('👩‍🦳', '白髪の女性', hasSkinTone: true),
    Emoji('👩‍🦲', 'はげ頭の女性', hasSkinTone: true),
    Emoji('🧓', '高齢者', hasSkinTone: true),
    Emoji('👴', 'おじいさん', hasSkinTone: true),
    Emoji('👵', 'おばあさん', hasSkinTone: true),
    Emoji('🙍‍♂️', '眉をひそめた男性', hasSkinTone: true),
    Emoji('🙍‍♀️', '眉をひそめた女性', hasSkinTone: true),
    Emoji('🙎‍♂️', 'ふくれっ面の男性', hasSkinTone: true),
    Emoji('🙎‍♀️', 'ふくれっ面の女性', hasSkinTone: true),
    Emoji('🙅‍♂️', '拒否のジェスチャーをする男性', hasSkinTone: true),
    Emoji('🙅‍♀️', '拒否のジェスチャーをする女性', hasSkinTone: true),
    Emoji('🙆‍♂️', 'OKのジェスチャーをする男性', hasSkinTone: true),
    Emoji('🙆‍♀️', 'OKのジェスチャーをする女性', hasSkinTone: true),
    Emoji('💁‍♂️', '案内する男性', hasSkinTone: true),
    Emoji('💁‍♀️', '案内する女性', hasSkinTone: true),
    Emoji('🙋‍♂️', '手を挙げる男性', hasSkinTone: true),
    Emoji('🙋‍♀️', '手を挙げる女性', hasSkinTone: true),
    Emoji('🙇‍♂️', 'お辞儀をする男性', hasSkinTone: true),
    Emoji('🙇‍♀️', 'お辞儀をする女性', hasSkinTone: true),
    Emoji('🤦‍♂️', '顔に手を当てる男性', hasSkinTone: true),
    Emoji('🤦‍♀️', '顔に手を当てる女性', hasSkinTone: true),
    Emoji('🤷‍♂️', '肩をすくめる男性', hasSkinTone: true),
    Emoji('🤷‍♀️', '肩をすくめる女性', hasSkinTone: true),
    Emoji('👨‍⚕️', '男性医療従事者', hasSkinTone: true),
    Emoji('👩‍⚕️', '女性医療従事者', hasSkinTone: true),
    Emoji('👨‍🎓', '男子学生', hasSkinTone: true),
    Emoji('👩‍🎓', '女子学生', hasSkinTone: true),
    Emoji('👨‍🏫', '男性教師', hasSkinTone: true),
    Emoji('👩‍🏫', '女性教師', hasSkinTone: true),
    Emoji('👨‍⚖️', '男性裁判官', hasSkinTone: true),
    Emoji('👩‍⚖️', '女性裁判官', hasSkinTone: true),
    Emoji('👨‍🌾', '男性農家', hasSkinTone: true),
    Emoji('👩‍🌾', '女性農家', hasSkinTone: true),
    Emoji('👮‍♂️', '男性警察官', hasSkinTone: true),
    Emoji('👮‍♀️', '女性警察官', hasSkinTone: true),
    Emoji('🕵️‍♂️', '男性探偵', hasSkinTone: true),
    Emoji('🕵️‍♀️', '女性探偵', hasSkinTone: true),
    Emoji('💂‍♂️', '男性衛兵', hasSkinTone: true),
    Emoji('💂‍♀️', '女性衛兵', hasSkinTone: true),
    Emoji('👷‍♂️', '男性建設作業員', hasSkinTone: true),
    Emoji('👷‍♀️', '女性建設作業員', hasSkinTone: true),
    Emoji('🤴', '王子', hasSkinTone: true),
    Emoji('👸', '王女', hasSkinTone: true),
    Emoji('👳‍♂️', 'ターバンを巻いた男性', hasSkinTone: true),
    Emoji('👳‍♀️', 'ターバンを巻いた女性', hasSkinTone: true),
    Emoji('👲', '中国帽をかぶった男性', hasSkinTone: true),
    Emoji('🧕', 'ヘッドスカーフをかぶった女性', hasSkinTone: true),
    Emoji('🤵', 'タキシードを着た男性', hasSkinTone: true),
    Emoji('👰', 'ベールをかぶった花嫁', hasSkinTone: true),
    Emoji('🤰', '妊娠中の女性', hasSkinTone: true),
    Emoji('🤱', '授乳中の女性', hasSkinTone: true),
    Emoji('👼', '天使の赤ちゃん', hasSkinTone: true),
    Emoji('🎅', 'サンタクロース', hasSkinTone: true),
    Emoji('🤶', 'ミセスクロース', hasSkinTone: true),
    Emoji('🦸‍♂️', '男性スーパーヒーロー', hasSkinTone: true),
    Emoji('🦸‍♀️', '女性スーパーヒーロー', hasSkinTone: true),
    Emoji('🦹‍♂️', '男性スーパーヴィラン', hasSkinTone: true),
    Emoji('🦹‍♀️', '女性スーパーヴィラン', hasSkinTone: true),
    Emoji('🧙‍♂️', '男性魔術師', hasSkinTone: true),
    Emoji('🧙‍♀️', '女性魔術師', hasSkinTone: true),
    Emoji('🧚‍♂️', '男性妖精', hasSkinTone: true),
    Emoji('🧚‍♀️', '女性妖精', hasSkinTone: true),
    Emoji('🧛‍♂️', '男性吸血鬼', hasSkinTone: true),
    Emoji('🧛‍♀️', '女性吸血鬼', hasSkinTone: true),
    Emoji('🧜‍♂️', '男性人魚', hasSkinTone: true),
    Emoji('🧜‍♀️', '女性人魚', hasSkinTone: true),
    Emoji('🧝‍♂️', '男性エルフ', hasSkinTone: true),
    Emoji('🧝‍♀️', '女性エルフ', hasSkinTone: true),
    Emoji('🧞‍♂️', '男性魔人'),
    Emoji('🧞‍♀️', '女性魔人'),
    Emoji('🧟‍♂️', '男性ゾンビ'),
    Emoji('🧟‍♀️', '女性ゾンビ'),
    Emoji('💆‍♂️', 'マッサージを受ける男性', hasSkinTone: true),
    Emoji('💆‍♀️', 'マッサージを受ける女性', hasSkinTone: true),
    Emoji('💇‍♂️', '散髪する男性', hasSkinTone: true),
    Emoji('💇‍♀️', '散髪する女性', hasSkinTone: true),
    Emoji('🚶‍♂️', '歩く男性', hasSkinTone: true),
    Emoji('🚶‍♀️', '歩く女性', hasSkinTone: true),
    Emoji('🏃‍♂️', '走る男性', hasSkinTone: true),
    Emoji('🏃‍♀️', '走る女性', hasSkinTone: true),
    Emoji('🕺', '踊る男性', hasSkinTone: true),
    Emoji('💃', '踊る女性', hasSkinTone: true),
    Emoji('🕴️', '浮遊するスーツ姿の男性', hasSkinTone: true),
    Emoji('👯‍♂️', 'ウサギの耳をつけた男性たち'),
    Emoji('👯‍♀️', 'ウサギの耳をつけた女性たち'),
    Emoji('🧖‍♂️', 'サウナにいる男性', hasSkinTone: true),
    Emoji('🧖‍♀️', 'サウナにいる女性', hasSkinTone: true),
    Emoji('🧘', '座禅を組む人', hasSkinTone: true),
    Emoji('👭', '手をつなぐ女性たち', hasSkinTone: true),
    Emoji('👫', '手をつなぐ男女', hasSkinTone: true),
    Emoji('👬', '手をつなぐ男性たち', hasSkinTone: true),
    Emoji('💏', 'キス'),
    Emoji('👨‍❤️‍💋‍👨', '男性同士のキス'),
    Emoji('👩‍❤️‍💋‍👩', '女性同士のキス'),
    Emoji('💑', 'ハートのあるカップル'),
    Emoji('👨‍❤️‍👨', 'ハートのある男性のカップル'),
    Emoji('👩‍❤️‍👩', 'ハートのある女性のカップル'),
    Emoji('👪', '家族'),
    Emoji('👨‍👩‍👦', '家族：男性、女性、男の子'),
    Emoji('👨‍👩‍👧', '家族：男性、女性、女の子'),
    Emoji('👨‍👩‍👧‍👦', '家族：男性、女性、女の子、男の子'),
    Emoji('👨‍👩‍👦‍👦', '家族：男性、女性、男の子、男の子'),
    Emoji('👨‍👩‍👧‍👧', '家族：男性、女性、女の子、女の子'),
    Emoji('👨‍👨‍👦', '家族：男性、男性、男の子'),
    Emoji('👨‍👨‍👧', '家族：男性、男性、女の子'),
    Emoji('👨‍👨‍👧‍👦', '家族：男性、男性、女の子、男の子'),
    Emoji('👨‍👨‍👦‍👦', '家族：男性、男性、男の子、男の子'),
    Emoji('👨‍👨‍👧‍👧', '家族：男性、男性、女の子、女の子'),
    Emoji('👩‍👩‍👦', '家族：女性、女性、男の子'),
    Emoji('👩‍👩‍👧', '家族：女性、女性、女の子'),
    Emoji('👩‍👩‍👧‍👦', '家族：女性、女性、女の子、男の子'),
    Emoji('👩‍👩‍👦‍👦', '家族：女性、女性、男の子、男の子'),
    Emoji('👩‍👩‍👧‍👧', '家族：女性、女性、女の子、女の子'),
    Emoji('👨‍👦', '家族：男性、男の子'),
    Emoji('👨‍👦‍👦', '家族：男性、男の子、男の子'),
    Emoji('👨‍👧', '家族：男性、女の子'),
    Emoji('👨‍👧‍👦', '家族：男性、女の子、男の子'),
    Emoji('👨‍👧‍👧', '家族：男性、女の子、女の子'),
    Emoji('👩‍👦', '家族：女性、男の子'),
    Emoji('👩‍👦‍👦', '家族：女性、男の子、男の子'),
    Emoji('👩‍👧', '家族：女性、女の子'),
    Emoji('👩‍👧‍👦', '家族：女性、女の子、男の子'),
    Emoji('👩‍👧‍👧', '家族：女性、女の子、女の子'),
    Emoji('🗣️', '話す頭'),
    Emoji('👤', 'シルエットの胸像'),
    Emoji('👥', 'シルエットの胸像（複数）'),
    Emoji('🫂', 'ハグする人たち'),
    Emoji('👣', '足跡'),
    Emoji('🧳', 'スーツケース'),
    Emoji('🌂', '閉じた傘'),
    Emoji('☂️', '傘'),
    Emoji('🧵', '糸'),
    Emoji('🧶', '毛糸'),
    Emoji('👓', '眼鏡'),
    Emoji('🕶️', 'サングラス'),
    Emoji('🥽', 'ゴーグル'),
    Emoji('🥼', '白衣'),
    Emoji('👔', 'ネクタイ'),
    Emoji('👕', 'Tシャツ'),
    Emoji('👖', 'ジーンズ'),
    Emoji('🧣', 'マフラー'),
    Emoji('🧤', '手袋'),
    Emoji('🧥', 'コート'),
    Emoji('🧦', '靴下'),
    Emoji('👗', 'ドレス'),
    Emoji('👘', '着物'),
    Emoji('👙', 'ビキニ'),
    Emoji('👚', '女性服'),
    Emoji('👛', 'がま口財布'),
    Emoji('👜', 'ハンドバッグ'),
    Emoji('👝', 'クラッチバッグ'),
    Emoji('🎒', 'リュックサック'),
    Emoji('👞', '男性用靴'),
    Emoji('👟', 'ランニングシューズ'),
    Emoji('🥾', 'ハイキングブーツ'),
    Emoji('🥿', 'フラットシューズ'),
    Emoji('👠', 'ハイヒール'),
    Emoji('👡', '女性用サンダル'),
    Emoji('👢', '女性用ブーツ'),
    Emoji('👑', '王冠'),
    Emoji('👒', '女性用帽子'),
    Emoji('🎩', 'シルクハット'),
    Emoji('🎓', '卒業式の帽子'),
    Emoji('🧢', '野球帽'),
    Emoji('⛑️', '救助隊員のヘルメット'),
    Emoji('💄', '口紅'),
    Emoji('💍', '指輪'),
    Emoji('💼', 'ブリーフケース'),
  ]),

// ======================================================= Category.ANIMALS
  CategoryEmoji(Category.ANIMALS, [
    Emoji('🐶', '犬の顔'),
    Emoji('🐱', '猫の顔'),
    Emoji('🐭', 'ネズミの顔'),
    Emoji('🐹', 'ハムスターの顔'),
    Emoji('🐰', 'ウサギの顔'),
    Emoji('🦊', 'キツネの顔'),
    Emoji('🐻', 'クマの顔'),
    Emoji('🐼', 'パンダの顔'),
    Emoji('🐨', 'コアラの顔'),
    Emoji('🐯', 'トラの顔'),
    Emoji('🦁', 'ライオンの顔'),
    Emoji('🐮', '牛の顔'),
    Emoji('🐷', '豚の顔'),
    Emoji('🐽', '豚の鼻'),
    Emoji('🐸', 'カエルの顔'),
    Emoji('🐵', 'サルの顔'),
    Emoji('🙈', '見ざる'),
    Emoji('🙉', '聞かざる'),
    Emoji('🙊', '言わざる'),
    Emoji('🐒', 'サル'),
    Emoji('💥', '衝突'),
    Emoji('💫', '目が回る'),
    Emoji('💦', '汗の雫'),
    Emoji('💨', '疾走'),
    Emoji('🦍', 'ゴリラ'),
    Emoji('🐕', '犬'),
    Emoji('🐩', 'プードル'),
    Emoji('🐺', 'オオカミの顔'),
    Emoji('🦝', 'アライグマ'),
    Emoji('🐈', '猫'),
    Emoji('🐅', 'トラ'),
    Emoji('🐆', 'ヒョウ'),
    Emoji('🐴', '馬の顔'),
    Emoji('🐎', '馬'),
    Emoji('🦄', 'ユニコーンの顔'),
    Emoji('🦓', 'シマウマ'),
    Emoji('🐂', '雄牛'),
    Emoji('🐃', '水牛'),
    Emoji('🐄', '牛'),
    Emoji('🐖', '豚'),
    Emoji('🐗', 'イノシシ'),
    Emoji('🐏', '雄羊'),
    Emoji('🐑', '雌羊'),
    Emoji('🐐', 'ヤギ'),
    Emoji('🐪', 'ヒトコブラクダ'),
    Emoji('🐫', 'フタコブラクダ'),
    Emoji('🦙', 'ラマ'),
    Emoji('🦒', 'キリン'),
    Emoji('🐘', 'ゾウ'),
    Emoji('🦏', 'サイ'),
    Emoji('🦛', 'カバ'),
    Emoji('🐁', 'ハツカネズミ'),
    Emoji('🐀', 'ネズミ'),
    Emoji('🐇', 'ウサギ'),
    Emoji('🐿️', 'シマリス'),
    Emoji('🦔', 'ハリネズミ'),
    Emoji('🦇', 'コウモリ'),
    Emoji('🦘', 'カンガルー'),
    Emoji('🦡', 'アナグマ'),
    Emoji('🐾', '足跡'),
    Emoji('🦃', '七面鳥'),
    Emoji('🐔', 'ニトリ'),
    Emoji('🐓', 'オンドリ'),
    Emoji('🐣', '孵化するヒヨコ'),
    Emoji('🐤', 'ヒヨコ'),
    Emoji('🐥', '正面ヒヨコ'),
    Emoji('🐦', '鳥'),
    Emoji('🐧', 'ペンギン'),
    Emoji('🕊️', 'ハト'),
    Emoji('🦅', 'ワシ'),
    Emoji('🦆', 'アヒル'),
    Emoji('🦢', '白鳥'),
    Emoji('🦉', 'フクロウ'),
    Emoji('🦚', 'クジャク'),
    Emoji('🦜', 'オウム'),
    Emoji('🐊', 'ワニ'),
    Emoji('🐢', 'カメ'),
    Emoji('🦎', 'トカゲ'),
    Emoji('🐍', 'ヘビ'),
    Emoji('🐲', 'ドラゴンの顔'),
    Emoji('🐉', 'ドラゴン'),
    Emoji('🦕', '竜脚類'),
    Emoji('🦖', 'Tレックス'),
    Emoji('🧌', 'トロール'),
    Emoji('🐳', '潮を吹くクジラ'),
    Emoji('🐋', 'クジラ'),
    Emoji('🐬', 'イルカ'),
    Emoji('🐟', '魚'),
    Emoji('🐠', '熱帯魚'),
    Emoji('🐡', 'フグ'),
    Emoji('🦈', 'サメ'),
    Emoji('🐙', 'タコ'),
    Emoji('🪹', '空の巣'),
    Emoji('🪺', '卵のある巣'),
    Emoji('🐚', '巻貝'),
    Emoji('🪸', 'サンゴ'),
    Emoji('🐌', 'カタツムリ'),
    Emoji('🦋', 'チョウ'),
    Emoji('🐛', 'イモムシ'),
    Emoji('🐜', 'アリ'),
    Emoji('🐝', 'ミツバチ'),
    Emoji('🐞', 'テントウムシ'),
    Emoji('🦗', 'コオロギ'),
    Emoji('🕷️', 'クモ'),
    Emoji('🕸️', 'クモの巣'),
    Emoji('🦂', 'サソリ'),
    Emoji('🦟', '蚊'),
    Emoji('🦠', '微生物'),
    Emoji('💐', '花束'),
    Emoji('🌸', '桜'),
    Emoji('💮', '白い花'),
    Emoji('🏵️', 'ロゼット'),
    Emoji('🪷', '蓮'),
    Emoji('🌹', 'バラ'),
    Emoji('🥀', '枯れた花'),
    Emoji('🌺', 'ハイビスカス'),
    Emoji('🌻', 'ヒマワリ'),
    Emoji('🌼', '花'),
    Emoji('🌷', 'チューリップ'),
    Emoji('🌱', '苗木'),
    Emoji('🌲', '常緑樹'),
    Emoji('🌳', '落葉樹'),
    Emoji('🌴', 'ヤシの木'),
    Emoji('🌵', 'サボテン'),
    Emoji('🌾', '稲穂'),
    Emoji('🌿', 'ハーブ'),
    Emoji('☘️', 'シャムロック'),
    Emoji('🍀', '四つ葉のクローバー'),
    Emoji('🍁', '紅葉'),
    Emoji('🍂', '落ち葉'),
    Emoji('🍃', '風に舞う葉'),
    Emoji('🍄', 'キノコ'),
    Emoji('🌰', '栗'),
    Emoji('🦀', 'カニ'),
    Emoji('🦞', 'ロブスター'),
    Emoji('🦐', 'エビ'),
    Emoji('🦑', 'イカ'),
    Emoji('🌍', 'ヨーロッパ・アフリカの地球'),
    Emoji('🌎', 'アメリカ大陸の地球'),
    Emoji('🌏', 'アジア・オーストラリアの地球'),
    Emoji('🌐', '経線のある地球'),
    Emoji('🌑', '新月'),
    Emoji('🌒', '三日月'),
    Emoji('🌓', '上弦の月'),
    Emoji('🌔', '十三夜月'),
    Emoji('🌕', '満月'),
    Emoji('🌖', '十六夜月'),
    Emoji('🌗', '下弦の月'),
    Emoji('🌘', '二十六夜月'),
    Emoji('🌙', '三日月'),
    Emoji('🌚', '新月の顔'),
    Emoji('🌛', '上弦の月の顔'),
    Emoji('🌜', '下弦の月の顔'),
    Emoji('☀️', '太陽'),
    Emoji('🌝', '満月の顔'),
    Emoji('🌞', '顔のある太陽'),
    Emoji('⭐', '星'),
    Emoji('🌟', '輝く星'),
    Emoji('🌠', '流れ星'),
    Emoji('☁️', '雲'),
    Emoji('⛅', '雲のかかった太陽'),
    Emoji('⛈️', '雷雨の雲'),
    Emoji('🌤️', '晴れ'),
    Emoji('🌥️', '曇り'),
    Emoji('🌦️', '曇り時々雨'),
    Emoji('🌧️', '雨雲'),
    Emoji('🌨️', '雪雲'),
    Emoji('🌩️', '雷雲'),
    Emoji('🌪️', '竜巻'),
    Emoji('🌫️', '霧'),
    Emoji('🌬️', '風の顔'),
    Emoji('🌈', '虹'),
    Emoji('☂️', '傘'),
    Emoji('☔', '雨の傘'),
    Emoji('⚡', '高電圧'),
    Emoji('❄️', '雪の結晶'),
    Emoji('☃️', '雪だるま'),
    Emoji('⛄', '雪のない雪だるま'),
    Emoji('☄️', '彗星'),
    Emoji('🔥', '火'),
    Emoji('💧', '水滴'),
    Emoji('🫧', '泡'),
    Emoji('🌊', '波'),
    Emoji('🎄', 'クリスマスツリー'),
    Emoji('✨', 'キラキラ'),
    Emoji('🎋', '七夕飾り'),
    Emoji('🎍', '門松')
  ]),

// ======================================================= Category.FOODS
  CategoryEmoji(Category.FOODS, [
    Emoji('🍇', 'ぶどう'),
    Emoji('🍈', 'メロン'),
    Emoji('🍉', 'スイカ'),
    Emoji('🍊', 'みかん'),
    Emoji('🍋', 'レモン'),
    Emoji('🍌', 'バナナ'),
    Emoji('🍍', 'パイナップル'),
    Emoji('🥭', 'マンゴー'),
    Emoji('🍎', '赤りんご'),
    Emoji('🍏', '青りんご'),
    Emoji('🍐', '洋ナシ'),
    Emoji('🍑', '桃'),
    Emoji('🍒', 'さくらんぼ'),
    Emoji('🍓', 'いちご'),
    Emoji('🥝', 'キウイフルーツ'),
    Emoji('🍅', 'トマト'),
    Emoji('🥥', 'ココナッツ'),
    Emoji('🥑', 'アボカド'),
    Emoji('🍆', 'ナス'),
    Emoji('🥔', 'じゃがいも'),
    Emoji('🥕', 'にんじん'),
    Emoji('🌽', 'とうもろこし'),
    Emoji('🌶️', '唐辛子'),
    Emoji('🥒', 'きゅうり'),
    Emoji('🥬', '葉野菜'),
    Emoji('🥦', 'ブロッコリー'),
    Emoji('🍄', 'きのこ'),
    Emoji('🥜', 'ピーナッツ'),
    Emoji('🫘', '豆'),
    Emoji('🌰', '栗'),
    Emoji('🍞', 'パン'),
    Emoji('🥐', 'クロワッサン'),
    Emoji('🥖', 'バゲット'),
    Emoji('🥨', 'プレッツェル'),
    Emoji('🥯', 'ベーグル'),
    Emoji('🥞', 'パンケーキ'),
    Emoji('🧀', 'チーズ'),
    Emoji('🍖', '骨付き肉'),
    Emoji('🍗', '鶏肉'),
    Emoji('🥩', 'ステーキ'),
    Emoji('🥓', 'ベーコン'),
    Emoji('🍔', 'ハンバーガー'),
    Emoji('🍟', 'フライドポテト'),
    Emoji('🍕', 'ピザ'),
    Emoji('🌭', 'ホットドッグ'),
    Emoji('🥪', 'サンドイッチ'),
    Emoji('🌮', 'タコス'),
    Emoji('🌯', 'ブリトー'),
    Emoji('🥙', '詰め物入りフラットブレッド'),
    Emoji('🍳', '料理'),
    Emoji('🥘', '浅鍋料理'),
    Emoji('🍲', '鍋料理'),
    Emoji('🥣', 'スプーン付きボウル'),
    Emoji('🥗', 'グリーンサラダ'),
    Emoji('🍿', 'ポップコーン'),
    Emoji('🧂', '塩'),
    Emoji('🥫', '缶詰'),
    Emoji('🫙', '瓶'),
    Emoji('🍱', '弁当'),
    Emoji('🍘', 'せんべい'),
    Emoji('🍙', 'おにぎり'),
    Emoji('🍚', 'ご飯'),
    Emoji('🍛', 'カレーライス'),
    Emoji('🍜', 'ラーメン'),
    Emoji('🍝', 'スパゲッティ'),
    Emoji('🍠', '焼き芋'),
    Emoji('🍢', 'おでん'),
    Emoji('🍣', '寿司'),
    Emoji('🍤', 'エビフライ'),
    Emoji('🍥', 'かまぼこ'),
    Emoji('🥮', '月餅'),
    Emoji('🍡', '団子'),
    Emoji('🥟', '餃子'),
    Emoji('🥠', 'フォーチュンクッキー'),
    Emoji('🥡', '持ち帰り用ボックス'),
    Emoji('🍦', 'ソフトクリーム'),
    Emoji('🍧', 'かき氷'),
    Emoji('🍨', 'アイスクリーム'),
    Emoji('🍩', 'ドーナツ'),
    Emoji('🍪', 'クッキー'),
    Emoji('🎂', '誕生日ケーキ'),
    Emoji('🍰', 'ショートケーキ'),
    Emoji('🧁', 'カップケーキ'),
    Emoji('🥧', 'パイ'),
    Emoji('🍫', 'チョコレート'),
    Emoji('🍬', 'キャンディ'),
    Emoji('🍭', 'ロリポップ'),
    Emoji('🍮', 'プリン'),
    Emoji('🍯', 'ハチミツ'),
    Emoji('🍼', '哺乳瓶'),
    Emoji('🥛', '牛乳'),
    Emoji('🫗', '液体を注ぐ'),
    Emoji('☕', 'ホットドリンク'),
    Emoji('🍵', '湯呑み'),
    Emoji('🧉', 'マテ茶'),
    Emoji('🍶', '日本酒'),
    Emoji('🍾', 'シャンパン'),
    Emoji('🍷', 'ワイングラス'),
    Emoji('🍸', 'カクテルグラス'),
    Emoji('🍹', 'トロピカルドリンク'),
    Emoji('🍺', 'ビールジョッキ'),
    Emoji('🍻', '乾杯'),
    Emoji('🥂', '乾杯'),
    Emoji('🥃', 'タンブラーグラス'),
    Emoji('🥤', 'ストロー付きカップ'),
    Emoji('🥢', '箸'),
    Emoji('🍽️', 'フォークとナイフと皿'),
    Emoji('🍴', 'フォークとナイフ'),
    Emoji('🥄', 'スプーン')
  ]),

// ======================================================= Category.TRAVEL
  CategoryEmoji(Category.TRAVEL, [
    Emoji('🗾', '日本地図'),
    Emoji('🏔️', '雪山'),
    Emoji('⛰️', '山'),
    Emoji('🌋', '火山'),
    Emoji('🗻', '富士山'),
    Emoji('🏕️', 'キャンプ'),
    Emoji('🏖️', 'ビーチパラソル'),
    Emoji('🏜️', '砂漠'),
    Emoji('🏝️', '無人島'),
    Emoji('🏞️', '国立公園'),
    Emoji('🏟️', 'スタジアム'),
    Emoji('🏛️', '古代建築'),
    Emoji('🏗️', '建設中'),
    Emoji('🏘️', '家々'),
    Emoji('🏚️', '廃墟'),
    Emoji('🏠', '家'),
    Emoji('🏡', '庭付きの家'),
    Emoji('🏢', 'オフィスビル'),
    Emoji('🏣', '郵便局'),
    Emoji('🏤', '郵便局'),
    Emoji('🏥', '病院'),
    Emoji('🏦', '銀行'),
    Emoji('🏨', 'ホテル'),
    Emoji('🏩', 'ラブホテル'),
    Emoji('🏪', 'コンビニ'),
    Emoji('🏫', '学校'),
    Emoji('🏬', 'デパート'),
    Emoji('🏭', '工場'),
    Emoji('🏯', '城'),
    Emoji('🏰', '城'),
    Emoji('💒', '結婚式'),
    Emoji('🗼', '東京タワー'),
    Emoji('🗽', '自由の女神'),
    Emoji('⛪', '教会'),
    Emoji('🕌', 'モスク'),
    Emoji('🕍', 'シナゴーグ'),
    Emoji('⛩️', '神社'),
    Emoji('🕋', 'カーバ神殿'),
    Emoji('⛲', '噴水'),
    Emoji('⛺', 'テント'),
    Emoji('🌁', '霧'),
    Emoji('🌃', '星空'),
    Emoji('🏙️', '都会の風景'),
    Emoji('🌄', '日の出'),
    Emoji('🌅', '日の出'),
    Emoji('🌆', '夕暮れの都会'),
    Emoji('🌇', '夕日'),
    Emoji('🌉', '夜の橋'),
    Emoji('🎠', 'メリーゴーランド'),
    Emoji('🎡', '観覧車'),
    Emoji('🎢', 'ジェットコースター'),
    Emoji('🚂', '機関車'),
    Emoji('🚃', '電車'),
    Emoji('🚄', '新幹線'),
    Emoji('🚅', '新幹線'),
    Emoji('🚆', '電車'),
    Emoji('🚇', '地下鉄'),
    Emoji('🚈', '路面電車'),
    Emoji('🚉', '駅'),
    Emoji('🚊', '路面電車'),
    Emoji('🚝', 'モノレール'),
    Emoji('🚞', '山岳鉄道'),
    Emoji('🚋', '路面電車'),
    Emoji('🚌', 'バス'),
    Emoji('🚍', '対向バス'),
    Emoji('🚎', 'トロリーバス'),
    Emoji('🚐', 'ミニバス'),
    Emoji('🚑', '救急車'),
    Emoji('🚒', '消防車'),
    Emoji('🚓', 'パトカー'),
    Emoji('🚔', '対向パトカー'),
    Emoji('🚕', 'タクシー'),
    Emoji('🚖', '対向タクシー'),
    Emoji('🚗', '車'),
    Emoji('🚘', '対向車'),
    Emoji('🚚', 'トラック'),
    Emoji('🚛', 'トレーラー'),
    Emoji('🚜', 'トラクター'),
    Emoji('🏎️', 'レーシングカー'),
    Emoji('🏍️', 'バイク'),
    Emoji('🛵', 'スクーター'),
    Emoji('🚲', '自転車'),
    Emoji('🛴', 'キックスクーター'),
    Emoji('🚏', 'バス停'),
    Emoji('🛤️', '線路'),
    Emoji('⛽', 'ガソリンスタンド'),
    Emoji('🛞', 'ホイール'),
    Emoji('🚨', 'パトライト'),
    Emoji('🚥', '信号'),
    Emoji('🚦', '信号'),
    Emoji('🚧', '工事中'),
    Emoji('⚓', '錨'),
    Emoji('⛵', 'ヨット'),
    Emoji('🚤', 'スピードボート'),
    Emoji('🛳️', '客船'),
    Emoji('⛴️', 'フェリー'),
    Emoji('🛥️', 'モーターボート'),
    Emoji('🚢', '船'),
    Emoji('🛟', '浮き輪'),
    Emoji('✈️', '飛行機'),
    Emoji('🛩️', '小型飛行機'),
    Emoji('🛫', '出発'),
    Emoji('🛬', '到着'),
    Emoji('💺', '座席'),
    Emoji('🚁', 'ヘリコプター'),
    Emoji('🚟', 'サスペンション鉄道'),
    Emoji('🚠', 'ケーブルカー'),
    Emoji('🚡', 'ロープウェイ'),
    Emoji('🛰️', '人工衛星'),
    Emoji('🚀', 'ロケット'),
    Emoji('🛸', '空飛ぶ円盤'),
    Emoji('🌠', '流れ星'),
    Emoji('🌌', '天の川'),
    Emoji('⛱️', 'ビーチパラソル'),
    Emoji('🎆', '花火'),
    Emoji('🎇', '線香花火'),
    Emoji('🎑', 'お月見'),
    Emoji('🗿', 'モアイ'),
    Emoji('🛂', 'パスポートコントロール'),
    Emoji('🛃', '税関'),
    Emoji('🛄', '手荷物受取所'),
    Emoji('🛅', '手荷物預かり所')
  ]),

// ======================================================= Category.ACTIVITIES
  CategoryEmoji(Category.ACTIVITIES, [
    Emoji('🧗‍♂️', 'クライミングをする男性', hasSkinTone: true),
    Emoji('🧗‍♀️', 'クライミングをする女性', hasSkinTone: true),
    Emoji('🏇', '競馬', hasSkinTone: true),
    Emoji('⛷️', 'スキーヤー'),
    Emoji('🏂', 'スノーボーダー'),
    Emoji('🏌️‍♂️', 'ゴルフをする男性', hasSkinTone: true),
    Emoji('🏌️‍♀️', 'ゴルフをする女性', hasSkinTone: true),
    Emoji('🏄‍♂️', 'サーフィンをする男性', hasSkinTone: true),
    Emoji('🏄‍♀️', 'サーフィンをする女性', hasSkinTone: true),
    Emoji('🚣‍♂️', 'ボートを漕ぐ男性', hasSkinTone: true),
    Emoji('🚣‍♀️', 'ボートを漕ぐ女性', hasSkinTone: true),
    Emoji('🏊‍♂️', '泳ぐ男性', hasSkinTone: true),
    Emoji('🏊‍♀️', '泳ぐ女性', hasSkinTone: true),
    Emoji('⛹️‍♂️', 'ボールを弾む男性', hasSkinTone: true),
    Emoji('⛹️‍♀️', 'ボールを弾む女性', hasSkinTone: true),
    Emoji('🏋️‍♂️', 'ウェイトリフティングをする男性', hasSkinTone: true),
    Emoji('🏋️‍♀️', 'ウェイトリフティングをする女性', hasSkinTone: true),
    Emoji('🚴‍♂️', '自転車に乗る男性', hasSkinTone: true),
    Emoji('🚴‍♀️', '自転車に乗る女性', hasSkinTone: true),
    Emoji('🚵‍♂️', 'マウンテンバイクに乗る男性', hasSkinTone: true),
    Emoji('🚵‍♀️', 'マウンテンバイクに乗る女性', hasSkinTone: true),
    Emoji('🤸‍♂️', '側転をする男性', hasSkinTone: true),
    Emoji('🤸‍♀️', '側転をする女性', hasSkinTone: true),
    Emoji('🤼‍♂️', 'レスリングをする男性', hasSkinTone: true),
    Emoji('🤼‍♀️', 'レスリングをする女性', hasSkinTone: true),
    Emoji('🤽‍♂️', '水球をする男性', hasSkinTone: true),
    Emoji('🤽‍♀️', '水球をする女性', hasSkinTone: true),
    Emoji('🤾‍♂️', 'ハンドボールをする男性', hasSkinTone: true),
    Emoji('🤾‍♀️', 'ハンドボールをする女性', hasSkinTone: true),
    Emoji('🤹‍♂️', 'ジャグリングをする男性', hasSkinTone: true),
    Emoji('🤹‍♀️', 'ジャグリングをする女性', hasSkinTone: true),
    Emoji('🧘‍♂️', '蓮華座の男性', hasSkinTone: true),
    Emoji('🧘‍♀️', '蓮華座の女性', hasSkinTone: true),
    Emoji('🎪', 'サーカス'),
    Emoji('🛹', 'スケートボード'),
    Emoji('🎗️', 'リボンの飾り'),
    Emoji('🎟️', '入場券'),
    Emoji('🎫', 'チケット'),
    Emoji('🎖️', '勲章'),
    Emoji('🏆', 'トロフィー'),
    Emoji('🏅', 'メダル'),
    Emoji('🥇', '金メダル'),
    Emoji('🥈', '銀メダル'),
    Emoji('🥉', '銅メダル'),
    Emoji('⚽', 'サッカーボール'),
    Emoji('⚾', '野球'),
    Emoji('🥎', 'ソフトボール'),
    Emoji('🏀', 'バスケットボール'),
    Emoji('🏐', 'バレーボール'),
    Emoji('🏈', 'アメリカンフットボール'),
    Emoji('🏉', 'ラグビーボール'),
    Emoji('🎾', 'テニス'),
    Emoji('🥏', 'フリスビー'),
    Emoji('🎳', 'ボーリング'),
    Emoji('🏏', 'クリケット'),
    Emoji('🏑', 'ホッケー'),
    Emoji('🏒', 'アイスホッケー'),
    Emoji('🥍', 'ラクロス'),
    Emoji('🏓', '卓球'),
    Emoji('🏸', 'バドミントン'),
    Emoji('🪃', 'ブーメラン'),
    Emoji('🥅', 'ゴールネット'),
    Emoji('⛳', '旗'),
    Emoji('🪁', '凧'),
    Emoji('🛝', '滑り台'),
    Emoji('🏹', '弓矢'),
    Emoji('🎣', '釣り竿'),
    Emoji('🤿 ', 'ダイビングマスク'),
    Emoji('🥊', 'ボクシンググローブ'),
    Emoji('🥋', '柔道着'),
    Emoji('🎽', 'ランニングシャツ'),
    Emoji('🛼', 'ローラースケート'),
    Emoji('🛷', 'ソリ'),
    Emoji('⛸️', 'アイススケート'),
    Emoji('🥌', 'カーリングストーン'),
    Emoji('🎿', 'スキー'),
    Emoji('🎯', 'ダーツ'),
    Emoji('🎱', 'ビリヤード'),
    Emoji('🎮', 'ゲーム'),
    Emoji('🎰', 'スロットマシン'),
    Emoji('🎲', 'サイコロ'),
    Emoji('🧩', 'ジグソーパズル'),
    Emoji('♟️', 'チェスの駒'),
    Emoji('🎭', '舞台芸術'),
    Emoji('🎨', '絵の具パレット'),
    Emoji('🧵', '糸'),
    Emoji('🧶', '毛糸'),
    Emoji('🎼', '楽譜'),
    Emoji('🎤', 'マイク'),
    Emoji('🎧', 'ヘッドホン'),
    Emoji('🎷', 'サックス'),
    Emoji('🎸', 'ギター'),
    Emoji('🎹', 'キーボード'),
    Emoji('🎺', 'トランペット'),
    Emoji('🎻', 'バイオリン'),
    Emoji('🥁', 'ドラム'),
    Emoji('🎬', '映画')
  ]),

// ======================================================= Category.OBJECTS
  CategoryEmoji(Category.OBJECTS, [
    Emoji('💌', 'ラブレター'),
    Emoji('🕳️', '穴'),
    Emoji('💣', '爆弾'),
    Emoji('🛀', '入浴中の人'),
    Emoji('🛌', 'ベッドにいる人'),
    Emoji('🏺', 'アンフォラ'),
    Emoji('🗺️', '世界地図'),
    Emoji('🧭', '方位磁石'),
    Emoji('🧱', 'レンガ'),
    Emoji('💈', '床屋の看板'),
    Emoji('🛢️', 'ドラム缶'),
    Emoji('🛎️', 'ベル'),
    Emoji('🧳', '荷物'),
    Emoji('⌛', '砂時計'),
    Emoji('⏳', '砂時計'),
    Emoji('⌚', '腕時計'),
    Emoji('⏰', '目覚まし時計'),
    Emoji('⏱️', 'ストップウォッチ'),
    Emoji('⏲️', 'タイマー'),
    Emoji('🕰️', '置時計'),
    Emoji('🌡️', '温度計'),
    Emoji('⛱️', 'ビーチパラソル'),
    Emoji('🧨', '爆竹'),
    Emoji('🎈', '風船'),
    Emoji('🎉', 'クラッカー'),
    Emoji('🎊', '紙吹雪'),
    Emoji('🎎', 'ひな人形'),
    Emoji('🎏', '鯉のぼり'),
    Emoji('🎐', '風鈴'),
    Emoji('🪩', 'ミラーボール'),
    Emoji('🧧', 'お年玉袋'),
    Emoji('🎀', 'リボン'),
    Emoji('🎁', 'プレゼント'),
    Emoji('🔮', '水晶玉'),
    Emoji('🧿', 'ナザールボンジュウ'),
    Emoji('🪬', 'ハムサ'),
    Emoji('🕹️', 'ジョイスティック'),
    Emoji('🧸', 'テディベア'),
    Emoji('🖼️', '額縁の絵'),
    Emoji('🧵', '糸'),
    Emoji('🧶', '毛糸'),
    Emoji('🛍️', 'ショッピングバッグ'),
    Emoji('📿', '数珠'),
    Emoji('💎', '宝石'),
    Emoji('📯', '郵便ラッパ'),
    Emoji('🎙️', 'スタジオマイク'),
    Emoji('🎚️', 'レベルスライダー'),
    Emoji('🎛️', 'コントロールノブ'),
    Emoji('📻', 'ラジオ'),
    Emoji('📱', '携帯電話'),
    Emoji('📲', '矢印付き携帯電話'),
    Emoji('☎️', '電話'),
    Emoji('📞', '受話器'),
    Emoji('📟', 'ポケベル'),
    Emoji('📠', 'FAX'),
    Emoji('🔋', 'バッテリー'),
    Emoji('🪫', 'バッテリー低下'),
    Emoji('🔌', 'プラグ'),
    Emoji('💻', 'ノートパソコン'),
    Emoji('🖥️', 'デスクトップパソコン'),
    Emoji('🖨️', 'プリンター'),
    Emoji('⌨️', 'キーボード'),
    Emoji('🖱️', 'マウス'),
    Emoji('🖲️', 'トラックボール'),
    Emoji('💽', 'フロッピーディスク'),
    Emoji('💾', 'フロッピーディスク'),
    Emoji('💿', 'CD'),
    Emoji('📀', 'DVD'),
    Emoji('🧮', 'そろばん'),
    Emoji('🎥', 'ムービーカメラ'),
    Emoji('🎞️', 'フィルム'),
    Emoji('📽️', '映写機'),
    Emoji('📺', 'テレビ'),
    Emoji('📷', 'カメラ'),
    Emoji('📸', 'フラッシュ付きカメラ'),
    Emoji('📹', 'ビデオカメラ'),
    Emoji('📼', 'ビデオテープ'),
    Emoji('🔍', '虫眼鏡'),
    Emoji('🔎', '虫眼鏡'),
    Emoji('🕯️', 'ろうそく'),
    Emoji('💡', '電球'),
    Emoji('🔦', '懐中電灯'),
    Emoji('🏮', '提灯'),
    Emoji('📔', 'ノート'),
    Emoji('📕', '閉じた本'),
    Emoji('📖', '開いた本'),
    Emoji('📗', '緑の本'),
    Emoji('📘', '青の本'),
    Emoji('📙', 'オレンジの本'),
    Emoji('📚', '本'),
    Emoji('📓', 'ノート'),
    Emoji('📃', 'ページ'),
    Emoji('📜', '巻物'),
    Emoji('📄', 'ページ'),
    Emoji('📰', '新聞'),
    Emoji('🗞️', '巻かれた新聞'),
    Emoji('📑', 'ブックマークタブ'),
    Emoji('🔖', 'ブックマーク'),
    Emoji('🏷️', 'ラベル'),
    Emoji('💰', 'お金の袋'),
    Emoji('💴', '円札'),
    Emoji('💵', 'ドル札'),
    Emoji('💶', 'ユーロ札'),
    Emoji('💷', 'ポンド札'),
    Emoji('💸', '羽のついたお金'),
    Emoji('💳', 'クレジットカード'),
    Emoji('🪪', 'IDカード'),
    Emoji('🧾', '領収書'),
    Emoji('✉️', '封筒'),
    Emoji('📧', 'Eメール'),
    Emoji('📨', '受信メール'),
    Emoji('📩', '矢印付き封筒'),
    Emoji('📤', '送信トレイ'),
    Emoji('📥', '受信トレイ'),
    Emoji('📦', '荷物'),
    Emoji('📫', '閉じた郵便受け箱'),
    Emoji('📪', '閉じた郵便受け箱'),
    Emoji('📬', '開いた郵便受け箱'),
    Emoji('📭', '開いた郵便受け箱'),
    Emoji('📮', 'ポスト'),
    Emoji('🗳️', '投票箱'),
    Emoji('✏️', '鉛筆'),
    Emoji('✒️', 'ペン先'),
    Emoji('🖋️', '万年筆'),
    Emoji('🖊️', 'ペン'),
    Emoji('🖌️', '絵筆'),
    Emoji('🖍️', 'クレヨン'),
    Emoji('📝', 'メモ'),
    Emoji('📁', 'ファイルフォルダ'),
    Emoji('📂', '開いたファイルフォルダ'),
    Emoji('🗂️', 'カードインデックス'),
    Emoji('📅', 'カレンダー'),
    Emoji('📆', 'カレンダー'),
    Emoji('🗒️', 'メモ帳'),
    Emoji('🗓️', 'カレンダー'),
    Emoji('📇', 'カードインデックス'),
    Emoji('📈', '上昇チャート'),
    Emoji('📉', '下降チャート'),
    Emoji('📊', '棒グラフ'),
    Emoji('📋', 'クリップボード'),
    Emoji('📌', '押しピン'),
    Emoji('📍', '丸い押しピン'),
    Emoji('📎', 'クリップ'),
    Emoji('🖇️', '繋がったクリップ'),
    Emoji('📏', '定規'),
    Emoji('📐', '三角定規'),
    Emoji('✂️', 'はさみ'),
    Emoji('🗃️', 'カードボックス'),
    Emoji('🗄️', 'ファイルキャビネット'),
    Emoji('🗑️', 'ゴミ箱'),
    Emoji('🔒', 'ロック'),
    Emoji('🔓', 'ロック解除'),
    Emoji('🔏', 'ペン付きロック'),
    Emoji('🔐', '鍵付きロック'),
    Emoji('🔑', '鍵'),
    Emoji('🗝️', '古い鍵'),
    Emoji('🔨', 'ハンマー'),
    Emoji('⛏️', 'つるはし'),
    Emoji('⚒️', 'ハンマーとつるはし'),
    Emoji('🛠️', 'ハンマーとレンチ'),
    Emoji('🔪', '包丁'),
    Emoji('🗡️', '短剣'),
    Emoji('⚔️', '交差した剣'),
    Emoji('🔫', '銃'),
    Emoji('🛡️', '盾'),
    Emoji('🔧', 'レンチ'),
    Emoji('🔩', 'ナットとボルト'),
    Emoji('⚙️', '歯車'),
    Emoji('🗜️', 'クランプ'),
    Emoji('⚖️', '天秤'),
    Emoji('🔗', 'リンク'),
    Emoji('⛓️', 'チェーン'),
    Emoji('🧰', 'ツールボックス'),
    Emoji('🧲', '磁石'),
    Emoji('⚗️', 'アランビック'),
    Emoji('🧪', '試験管'),
    Emoji('🧫', 'シャーレ'),
    Emoji('🧬', 'DNA'),
    Emoji('🔬', '顕微鏡'),
    Emoji('🩻', 'レントゲン'),
    Emoji('🔭', '望遠鏡'),
    Emoji('📡', 'アンテナ'),
    Emoji('💉', '注射器'),
    Emoji('💊', '薬'),
    Emoji('🚪', 'ドア'),
    Emoji('🛏️', 'ベッド'),
    Emoji('🛋️', 'ソファとランプ'),
    Emoji('🚽', 'トイレ'),
    Emoji('🚿', 'シャワー'),
    Emoji('🛁', 'バスタブ'),
    Emoji('🧴', 'ローションボトル'),
    Emoji('🧷', '安全ピン'),
    Emoji('🧹', 'ほうき'),
    Emoji('🧺', 'かご'),
    Emoji('🧻', 'トイレットペーパー'),
    Emoji('🧼', '石鹸'),
    Emoji('🧽', 'スポンジ'),
    Emoji('🧯', '消火器'),
    Emoji('🚬', 'タバコ'),
    Emoji('⚰️', '棺桶'),
    Emoji('⚱️', '骨壷'),
    Emoji('🚰', '飲料水')
  ]),

// ======================================================= Category.SYMBOLS
  CategoryEmoji(Category.SYMBOLS, [
    Emoji('💘', 'ハートに矢'),
    Emoji('💝', 'リボン付きハート'),
    Emoji('💖', 'きらきらハート'),
    Emoji('💗', '大きくなるハート'),
    Emoji('💓', '鼓動するハート'),
    Emoji('💞', '回転するハート'),
    Emoji('💕', 'ふたつのハート'),
    Emoji('💟', 'ハートの飾り'),
    Emoji('❣️', 'ハートの感嘆符'),
    Emoji('💔', '壊れたハート'),
    Emoji('❤️', '赤いハート'),
    Emoji('🧡', 'オレンジのハート'),
    Emoji('💛', '黄色のハート'),
    Emoji('💚', '緑のハート'),
    Emoji('💙', '青のハート'),
    Emoji('💜', '紫のハート'),
    Emoji('🖤', '黒いハート'),
    Emoji('💯', '満点'),
    Emoji('💢', '怒り'),
    Emoji('💬', '吹き出し'),
    Emoji('👁️‍🗨️', '吹き出しの中の目'),
    Emoji('🗯️', '怒りの吹き出し'),
    Emoji('💭', '考え事'),
    Emoji('💤', 'Zzz'),
    Emoji('💮', '白い花'),
    Emoji('♨️', '温泉'),
    Emoji('💈', '床屋の看板'),
    Emoji('🛑', '止まれ'),
    Emoji('🕛', '12時'),
    Emoji('🕧', '12時半'),
    Emoji('🕐', '1時'),
    Emoji('🕜', '1時半'),
    Emoji('🕑', '2時'),
    Emoji('🕝', '2時半'),
    Emoji('🕒', '3時'),
    Emoji('🕞', '3時半'),
    Emoji('🕓', '4時'),
    Emoji('🕟', '4時半'),
    Emoji('🕔', '5時'),
    Emoji('🕠', '5時半'),
    Emoji('🕕', '6時'),
    Emoji('🕡', '6時半'),
    Emoji('🕖', '7時'),
    Emoji('🕢', '7時半'),
    Emoji('🕗', '8時'),
    Emoji('🕣', '8時半'),
    Emoji('🕘', '9時'),
    Emoji('🕤', '9時半'),
    Emoji('🕙', '10時'),
    Emoji('🕥', '10時半'),
    Emoji('🕚', '11時'),
    Emoji('🕦', '11時半'),
    Emoji('🌀', 'サイクロン'),
    Emoji('♠️', 'スペード'),
    Emoji('♥️', 'ハート'),
    Emoji('♦️', 'ダイヤ'),
    Emoji('♣️', 'クラブ'),
    Emoji('🃏', 'ジョーカー'),
    Emoji('🀄', '麻雀の牌'),
    Emoji('🎴', '花札'),
    Emoji('🔇', 'ミュート'),
    Emoji('🔈', '音量小'),
    Emoji('🔉', '音量中'),
    Emoji('🔊', '音量大'),
    Emoji('📢', '拡声器'),
    Emoji('📣', 'メガホン'),
    Emoji('📯', '郵便ラッパ'),
    Emoji('🔔', 'ベル'),
    Emoji('🔕', 'ベルに斜線'),
    Emoji('🎵', '音符'),
    Emoji('🎶', '音符'),
    Emoji('🏧', 'ATM'),
    Emoji('🚮', 'ゴミ箱'),
    Emoji('🚰', '飲料水'),
    Emoji('♿', '車椅子'),
    Emoji('🩼', '松葉杖'),
    Emoji('🚹', '男子トイレ'),
    Emoji('🚺', '女子トイレ'),
    Emoji('🚻', 'トイレ'),
    Emoji('🚼', '赤ちゃん'),
    Emoji('🚾', 'トイレ'),
    Emoji('⚠️', '警告'),
    Emoji('🚸', '横断歩道'),
    Emoji('⛔', '進入禁止'),
    Emoji('🚫', '禁止'),
    Emoji('🚳', '自転車禁止'),
    Emoji('🚭', '禁煙'),
    Emoji('🚯', 'ゴミ捨て禁止'),
    Emoji('🚱', '飲料水ではない'),
    Emoji('🚷', '通行止め'),
    Emoji('🔞', '18歳未満禁止'),
    Emoji('☢️', '放射能'),
    Emoji('☣️', 'バイオハザード'),
    Emoji('⬆️', '上矢印'),
    Emoji('↗️', '右上矢印'),
    Emoji('➡️', '右矢印'),
    Emoji('↘️', '右下矢印'),
    Emoji('⬇️', '下矢印'),
    Emoji('↙️', '左下矢印'),
    Emoji('⬅️', '左矢印'),
    Emoji('↖️', '左上矢印'),
    Emoji('↕️', '上下矢印'),
    Emoji('↔️', '左右矢印'),
    Emoji('↩️', '左カーブ矢印'),
    Emoji('↪️', '右カーブ矢印'),
    Emoji('⤴️', '上カーブ矢印'),
    Emoji('⤵️', '下カーブ矢印'),
    Emoji('🔃', '時計回り矢印'),
    Emoji('🔄', '反時計回り矢印'),
    Emoji('🔙', '戻る矢印'),
    Emoji('🔚', '終了矢印'),
    Emoji('🔛', 'オン！矢印'),
    Emoji('🔜', 'もうすぐ矢印'),
    Emoji('🔝', 'トップ矢印'),
    Emoji('🛐', '礼拝所'),
    Emoji('⚛️', '原子記号'),
    Emoji('🕉️', 'オーム'),
    Emoji('✡️', 'ダビデの星'),
    Emoji('☸️', '法輪'),
    Emoji('☯️', '陰陽'),
    Emoji('✝️', 'ラテン十字'),
    Emoji('☦️', '正教会の十字架'),
    Emoji('☪️', '三日月と星'),
    Emoji('☮️', '平和'),
    Emoji('🕎', 'メノーラー'),
    Emoji('🔯', '六芒星'),
    Emoji('♈', '牡羊座'),
    Emoji('♉', '牡牛座'),
    Emoji('♊', '双子座'),
    Emoji('♋', '蟹座'),
    Emoji('♌', '獅子座'),
    Emoji('♍', '乙女座'),
    Emoji('♎', '天秤座'),
    Emoji('♏', '蠍座'),
    Emoji('♐', '射手座'),
    Emoji('♑', '山羊座'),
    Emoji('♒', '水瓶座'),
    Emoji('♓', '魚座'),
    Emoji('⛎', '蛇使い座'),
    Emoji('🔀', 'シャッフルボタン'),
    Emoji('🔁', 'リピートボタン'),
    Emoji('🔂', '1曲リピートボタン'),
    Emoji('▶️', '再生ボタン'),
    Emoji('⏩', '早送りボタン'),
    Emoji('◀️', '巻き戻しボタン'),
    Emoji('⏪', '早戻しボタン'),
    Emoji('🔼', '上ボタン'),
    Emoji('⏫', '早送りボタン'),
    Emoji('🔽', '下ボタン'),
    Emoji('⏬', '早戻しボタン'),
    Emoji('⏹️', '停止ボタン'),
    Emoji('⏏️', '取り出しボタン'),
    Emoji('🎦', '映画館'),
    Emoji('🔅', '暗くするボタン'),
    Emoji('🔆', '明るくするボタン'),
    Emoji('📶', 'アンテナバー'),
    Emoji('📳', 'バイブモード'),
    Emoji('📴', '電源オフ'),
    Emoji('♾️', '無限'),
    Emoji('♻️', 'リサイクル'),
    Emoji('🔱', 'トライデント'),
    Emoji('📛', '名札'),
    Emoji('🔰', '初心者マーク'),
    Emoji('⭕', '丸'),
    Emoji('✅', 'チェックマーク'),
    Emoji('☑️', 'チェックボックス'),
    Emoji('✔️', 'チェックマーク'),
    Emoji('❌', 'バツ印'),
    Emoji('❎', 'バツボタン'),
    Emoji('➕', 'プラス記号'),
    Emoji('➖', 'マイナス記号'),
    Emoji('➗', '割り算記号'),
    Emoji('✖️', '掛け算記号'),
    Emoji('🟰', 'イコール記号'),
    Emoji('➰', 'ループ'),
    Emoji('➿', '二重ループ'),
    Emoji('〽️', 'パート交代マーク'),
    Emoji('✳️', 'アスタリスク'),
    Emoji('✴️', '八芒星'),
    Emoji('❇️', 'キラキラ'),
    Emoji('‼️', '二重感嘆符'),
    Emoji('⁉️', '疑問符と感嘆符'),
    Emoji('❓', '疑問符'),
    Emoji('❔', '白い疑問符'),
    Emoji('❕', '感嘆符'),
    Emoji('❗', '感嘆符'),
    Emoji('©️', '著作権'),
    Emoji('®️', '登録商標'),
    Emoji('™️', '商標'),
    Emoji('#️⃣', 'ハッシュキー'),
    Emoji('0️⃣', '数字キー0'),
    Emoji('1️⃣', '数字キー1'),
    Emoji('2️⃣', '数字キー2'),
    Emoji('3️⃣', '数字キー3'),
    Emoji('4️⃣', '数字キー4'),
    Emoji('5️⃣', '数字キー5'),
    Emoji('6️⃣', '数字キー6'),
    Emoji('7️⃣', '数字キー7'),
    Emoji('8️⃣', '数字キー8'),
    Emoji('9️⃣', '数字キー9'),
    Emoji('🔟', '数字キー10'),
    Emoji('🔠', '大文字入力'),
    Emoji('🔡', '小文字入力'),
    Emoji('🔢', '数字入力'),
    Emoji('🔣', '記号入力'),
    Emoji('🔤', '文字入力'),
    Emoji('🅰️', 'Aボタン'),
    Emoji('🆎', 'ABボタン'),
    Emoji('🅱️', 'Bボタン'),
    Emoji('🆑', 'CLボタン'),
    Emoji('🆒', 'クールボタン'),
    Emoji('🆓', '無料ボタン'),
    Emoji('ℹ️', '情報'),
    Emoji('🆔', 'IDボタン'),
    Emoji('Ⓜ️', 'Mマーク'),
    Emoji('🆕', '新着ボタン'),
    Emoji('🆖', 'NGボタン'),
    Emoji('🅾️', 'Oボタン'),
    Emoji('🆗', 'OKボタン'),
    Emoji('🅿️', 'Pボタン'),
    Emoji('🆘', 'SOSボタン'),
    Emoji('🆙', 'アップボタン'),
    Emoji('🆚', 'VSボタン'),
    Emoji('🈁', 'ココボタン'),
    Emoji('🈂️', 'サービス料ボタン'),
    Emoji('🈷️', '月額ボタン'),
    Emoji('🈶', '有料ボタン'),
    Emoji('🈯', '予約済みボタン'),
    Emoji('🉐', 'お得ボタン'),
    Emoji('🈹', '割引ボタン'),
    Emoji('🈚', '無料ボタン'),
    Emoji('🈲', '禁止ボタン'),
    Emoji('🉑', '可能ボタン'),
    Emoji('🈸', '申請ボタン'),
    Emoji('🈴', '合格ボタン'),
    Emoji('🈳', '空室ボタン'),
    Emoji('㊗️', '祝ボタン'),
    Emoji('㊙️', '秘密ボタン'),
    Emoji('🈺', '営業中ボタン'),
    Emoji('🈵', '満室ボタン'),
    Emoji('🔴', '赤い丸'),
    Emoji('🔵', '青い丸'),
    Emoji('⚫', '黒い丸'),
    Emoji('⚪', '白い丸'),
    Emoji('⬛', '黒い四角'),
    Emoji('⬜', '白い四角'),
    Emoji('◼️', '黒い四角'),
    Emoji('◻️', '白い四角'),
    Emoji('◾', '黒い四角'),
    Emoji('◽', '白い四角'),
    Emoji('▪️', '黒い四角'),
    Emoji('▫️', '白い四角'),
    Emoji('🔶', 'オレンジのひし形'),
    Emoji('🔷', '青のひし形'),
    Emoji('🔸', 'オレンジのひし形'),
    Emoji('🔹', '青のひし形'),
    Emoji('🔺', '赤い三角'),
    Emoji('🔻', '赤い三角'),
    Emoji('💠', '点付きひし形'),
    Emoji('🔳', '白い四角ボタン'),
    Emoji('🔲', '黒い四角ボタン')
  ]),

// ======================================================= Category.FLAGS
  CategoryEmoji(Category.FLAGS, [
    Emoji('🏁', 'チェッカーフラッグ'),
    Emoji('🚩', '三角旗'),
    Emoji('🎌', '交差した旗'),
    Emoji('🏴', '黒旗'),
    Emoji('🏳️', '白旗'),
    Emoji('🏳️‍🌈', 'レインボーフラッグ'),
    Emoji('🏳️‍⚧️', 'トランスジェンダーフラッグ'),
    Emoji('🏴‍☠️', '海賊旗'),
    Emoji('🇦🇨', 'アセンション島の旗'),
    Emoji('🇦🇩', 'アンドラの旗'),
    Emoji('🇦🇪', 'アラブ首長国連邦の旗'),
    Emoji('🇦🇫', 'アフガニスタンの旗'),
    Emoji('🇦🇬', 'アンティグア・バーブーダの旗'),
    Emoji('🇦🇮', 'アンギラの旗'),
    Emoji('🇦🇱', 'アルバニアの旗'),
    Emoji('🇦🇲', 'アルメニアの旗'),
    Emoji('🇦🇴', 'アンゴラの旗'),
    Emoji('🇦🇶', '南極大陸の旗'),
    Emoji('🇦🇷', 'アルゼンチンの旗'),
    Emoji('🇦🇸', 'アメリカ領サモアの旗'),
    Emoji('🇦🇹', 'オーストリアの旗'),
    Emoji('🇦🇺', 'オーストラリアの旗'),
    Emoji('🇦🇼', 'アルバの旗'),
    Emoji('🇦🇽', 'オーランド諸島の旗'),
    Emoji('🇦🇿', 'アゼルバイジャンの旗'),
    Emoji('🇧🇦', 'ボスニア・ヘルツェゴビナの旗'),
    Emoji('🇧🇧', 'バルバドスの旗'),
    Emoji('🇧🇩', 'バングラデシュの旗'),
    Emoji('🇧🇪', 'ベルギーの旗'),
    Emoji('🇧🇫', 'ブルキナファソの旗'),
    Emoji('🇧🇬', 'ブルガリアの旗'),
    Emoji('🇧🇭', 'バーレーンの旗'),
    Emoji('🇧🇮', 'ブルンジの旗'),
    Emoji('🇧🇯', 'ベナンの旗'),
    Emoji('🇧🇱', 'サン・バルテルミーの旗'),
    Emoji('🇧🇲', 'バミューダの旗'),
    Emoji('🇧🇳', 'ブルネイの旗'),
    Emoji('🇧🇴', 'ボリビアの旗'),
    Emoji('🇧🇶', 'カリブ諸島の旗'),
    Emoji('🇧🇷', 'ブラジルの旗'),
    Emoji('🇧🇸', 'バハマの旗'),
    Emoji('🇧🇹', 'ブータンの旗'),
    Emoji('🇧🇻', 'ブーベ島の旗'),
    Emoji('🇧🇼', 'ボツワナの旗'),
    Emoji('🇧🇾', 'ベラルーシの旗'),
    Emoji('🇧🇿', 'ベリーズの旗'),
    Emoji('🇨🇦', 'カナダの旗'),
    Emoji('🇨🇨', 'ココス諸島の旗'),
    Emoji('🇨🇩', 'コンゴ民主共和国の旗'),
    Emoji('🇨🇫', '中央アフリカ共和国の旗'),
    Emoji('🇨🇬', 'コンゴ共和国の旗'),
    Emoji('🇨🇭', 'スイスの旗'),
    Emoji('🇨🇮', 'コートジボワールの旗'),
    Emoji('🇨🇰', 'クック諸島の旗'),
    Emoji('🇨🇱', 'チリの旗'),
    Emoji('🇨🇲', 'カメルーンの旗'),
    Emoji('🇨🇳', '中国の旗'),
    Emoji('🇨🇴', 'コロンビアの旗'),
    Emoji('🇨🇵', 'クリッパートン島の旗'),
    Emoji('🇨🇷', 'コスタリカの旗'),
    Emoji('🇨🇺', 'キューバの旗'),
    Emoji('🇨🇻', 'カーボベルデの旗'),
    Emoji('🇨🇼', 'キュラソーの旗'),
    Emoji('🇨🇽', 'クリスマス島の旗'),
    Emoji('🇨🇾', 'キプロスの旗'),
    Emoji('🇨🇿', 'チェコの旗'),
    Emoji('🇩🇪', 'ドイツの旗'),
    Emoji('🇩🇬', 'ディエゴガルシアの旗'),
    Emoji('🇩🇯', 'ジブチの旗'),
    Emoji('🇩🇰', 'デンマークの旗'),
    Emoji('🇩🇲', 'ドミニカ国の旗'),
    Emoji('🇩🇴', 'ドミニカ共和国の旗'),
    Emoji('🇩🇿', 'アルジェリアの旗'),
    Emoji('🇪🇦', 'セウタ・メリリャの旗'),
    Emoji('🇪🇨', 'エクアドルの旗'),
    Emoji('🇪🇪', 'エストニアの旗'),
    Emoji('🇪🇬', 'エジプトの旗'),
    Emoji('🇪🇭', '西サハラの旗'),
    Emoji('🇪🇷', 'エリトリアの旗'),
    Emoji('🇪🇸', 'スペインの旗'),
    Emoji('🇪🇹', 'エチオピアの旗'),
    Emoji('🇪🇺', 'EUの旗'),
    Emoji('🇫🇮', 'フィンランドの旗'),
    Emoji('🇫🇯', 'フィジーの旗'),
    Emoji('🇫🇰', 'フォークランド諸島の旗'),
    Emoji('🇫🇲', 'ミクロネシアの旗'),
    Emoji('🇫🇴', 'フェロー諸島の旗'),
    Emoji('🇫🇷', 'フランスの旗'),
    Emoji('🇬🇦', 'ガボンの旗'),
    Emoji('🇬🇧', 'イギリスの旗'),
    Emoji('🇬🇩', 'グレナダの旗'),
    Emoji('🇬🇪', 'ジョージアの旗'),
    Emoji('🇬🇫', 'フランス領ギアナの旗'),
    Emoji('🇬🇬', 'ガーンジーの旗'),
    Emoji('🇬🇭', 'ガーナの旗'),
    Emoji('🇬🇮', 'ジブラルタルの旗'),
    Emoji('🇬🇱', 'グリーンランドの旗'),
    Emoji('🇬🇲', 'ガンビアの旗'),
    Emoji('🇬🇳', 'ギニアの旗'),
    Emoji('🇬🇵', 'グアドループの旗'),
    Emoji('🇬🇶', '赤道ギニアの旗'),
    Emoji('🇬🇷', 'ギリシャの旗'),
    Emoji('🇬🇸', 'サウスジョージア・サウスサンドウィッチ諸島の旗'),
    Emoji('🇬🇹', 'グアテマラの旗'),
    Emoji('🇬🇺', 'グアムの旗'),
    Emoji('🇬🇼', 'ギニアビサウの旗'),
    Emoji('🇬🇾', 'ガイアナの旗'),
    Emoji('🇭🇰', '香港の旗'),
    Emoji('🇭🇲', 'ハード島とマクドナルド諸島の旗'),
    Emoji('🇭🇳', 'ホンジュラスの旗'),
    Emoji('🇭🇷', 'クロアチアの旗'),
    Emoji('🇭🇹', 'ハイチの旗'),
    Emoji('🇭🇺', 'ハンガリーの旗'),
    Emoji('🇮🇨', 'カナリア諸島の旗'),
    Emoji('🇮🇩', 'インドネシアの旗'),
    Emoji('🇮🇪', 'アイルランドの旗'),
    Emoji('🇮🇱', 'イスラエルの旗'),
    Emoji('🇮🇲', 'マン島の旗'),
    Emoji('🇮🇳', 'インドの旗'),
    Emoji('🇮🇴', 'イギリス領インド洋地域の旗'),
    Emoji('🇮🇶', 'イラクの旗'),
    Emoji('🇮🇷', 'イランの旗'),
    Emoji('🇮🇸', 'アイスランドの旗'),
    Emoji('🇮🇹', 'イタリアの旗'),
    Emoji('🇯🇪', 'ジャージーの旗'),
    Emoji('🇯🇲', 'ジャマイカの旗'),
    Emoji('🇯🇴', 'ヨルダンの旗'),
    Emoji('🇯🇵', '日本の旗'),
    Emoji('🇰🇪', 'ケニアの旗'),
    Emoji('🇰🇬', 'キルギスタンの旗'),
    Emoji('🇰🇭', 'カンボジアの旗'),
    Emoji('🇰🇮', 'キリバスの旗'),
    Emoji('🇰🇲', 'コモロの旗'),
    Emoji('🇰🇳', 'セントクリストファー・ネイビスの旗'),
    Emoji('🇰🇵', '北朝鮮の旗'),
    Emoji('🇰🇷', '韓国の旗'),
    Emoji('🇰🇼', 'クウェートの旗'),
    Emoji('🇰🇾', 'ケイマン諸島の旗'),
    Emoji('🇰🇿', 'カザフスタンの旗'),
    Emoji('🇱🇦', 'ラオスの旗'),
    Emoji('🇱🇧', 'レバノンの旗'),
    Emoji('🇱🇨', 'セントルシアの旗'),
    Emoji('🇱🇮', 'リヒテンシュタインの旗'),
    Emoji('🇱🇰', 'スリランカの旗'),
    Emoji('🇱🇷', 'リベリアの旗'),
    Emoji('🇱🇸', 'レソトの旗'),
    Emoji('🇱🇹', 'リトアニアの旗'),
    Emoji('🇱🇺', 'ルクセンブルクの旗'),
    Emoji('🇱🇻', 'ラトビアの旗'),
    Emoji('🇱🇾', 'リビアの旗'),
    Emoji('🇲🇦', 'モロッコの旗'),
    Emoji('🇲🇨', 'モナコの旗'),
    Emoji('🇲🇩', 'モルドバの旗'),
    Emoji('🇲🇪', 'モンテネグロの旗'),
    Emoji('🇲🇫', 'サン・マルタンの旗'),
    Emoji('🇲🇬', 'マダガスカルの旗'),
    Emoji('🇲🇭', 'マーシャル諸島の旗'),
    Emoji('🇲🇰', '北マケドニアの旗'),
    Emoji('🇲🇱', 'マリの旗'),
    Emoji('🇲🇲', 'ミャンマーの旗'),
    Emoji('🇲🇳', 'モンゴルの旗'),
    Emoji('🇲🇴', 'マカオの旗'),
    Emoji('🇲🇵', '北マリアナ諸島の旗'),
    Emoji('🇲🇶', 'マルティニークの旗'),
    Emoji('🇲🇷', 'モーリタニアの旗'),
    Emoji('🇲🇸', 'モントセラトの旗'),
    Emoji('🇲🇹', 'マルタの旗'),
    Emoji('🇲🇺', 'モーリシャスの旗'),
    Emoji('🇲🇻', 'モルディブの旗'),
    Emoji('🇲🇼', 'マラウイの旗'),
    Emoji('🇲🇽', 'メキシコの旗'),
    Emoji('🇲🇾', 'マレーシアの旗'),
    Emoji('🇲🇿', 'モザンビークの旗'),
    Emoji('🇳🇦', 'ナミビアの旗'),
    Emoji('🇳🇨', 'ニューカレドニアの旗'),
    Emoji('🇳🇪', 'ニジェールの旗'),
    Emoji('🇳🇫', 'ノーフォーク島の旗'),
    Emoji('🇳🇬', 'ナイジェリアの旗'),
    Emoji('🇳🇮', 'ニカラグアの旗'),
    Emoji('🇳🇱', 'オランダの旗'),
    Emoji('🇳🇴', 'ノルウェーの旗'),
    Emoji('🇳🇵', 'ネパールの旗'),
    Emoji('🇳🇷', 'ナウルの旗'),
    Emoji('🇳🇺', 'ニウエの旗'),
    Emoji('🇳🇿', 'ニュージーランドの旗'),
    Emoji('🇴🇲', 'オマーンの旗'),
    Emoji('🇵🇦', 'パナマの旗'),
    Emoji('🇵🇪', 'ペルーの旗'),
    Emoji('🇵🇫', 'フランス領ポリネシアの旗'),
    Emoji('🇵🇬', 'パプアニューギニアの旗'),
    Emoji('🇵🇭', 'フィリピンの旗'),
    Emoji('🇵🇰', 'パキスタンの旗'),
    Emoji('🇵🇱', 'ポーランドの旗'),
    Emoji('🇵🇲', 'サンピエール島・ミクロン島の旗'),
    Emoji('🇵🇳', 'ピトケアン諸島の旗'),
    Emoji('🇵🇷', 'プエルトリコの旗'),
    Emoji('🇵🇸', 'パレスチナの旗'),
    Emoji('🇵🇹', 'ポルトガルの旗'),
    Emoji('🇵🇼', 'パラオの旗'),
    Emoji('🇵🇾', 'パラグアイの旗'),
    Emoji('🇶🇦', 'カタールの旗'),
    Emoji('🇷🇪', 'レユニオンの旗'),
    Emoji('🇷🇴', 'ルーマニアの旗'),
    Emoji('🇷🇸', 'セルビアの旗'),
    Emoji('🇷🇺', 'ロシアの旗'),
    Emoji('🇷🇼', 'ルワンダの旗'),
    Emoji('🇸🇦', 'サウジアラビアの旗'),
    Emoji('🇸🇧', 'ソロモン諸島の旗'),
    Emoji('🇸🇨', 'セーシェル共和国の旗'),
    Emoji('🇸🇩', 'スーダンの旗'),
    Emoji('🇸🇪', 'スウェーデンの旗'),
    Emoji('🇸🇬', 'シンガポールの旗'),
    Emoji('🇸🇭', 'セントヘレナの旗'),
    Emoji('🇸🇮', 'スロベニアの旗'),
    Emoji('🇸🇯', 'スバールバル諸島・ヤンマイエン島の旗'),
    Emoji('🇸🇰', 'スロバキアの旗'),
    Emoji('🇸🇱', 'シエラレオネの旗'),
    Emoji('🇸🇲', 'サンマリノの旗'),
    Emoji('🇸🇳', 'セネガルの旗'),
    Emoji('🇸🇴', 'ソマリアの旗'),
    Emoji('🇸🇷', 'スリナムの旗'),
    Emoji('🇸🇸', '南スーダンの旗'),
    Emoji('🇸🇹', 'サントメ・プリンシペの旗'),
    Emoji('🇸🇻', 'エルサルバドルの旗'),
    Emoji('🇸🇽', 'シント・マールテンの旗'),
    Emoji('🇸🇾', 'シリアの旗'),
    Emoji('🇸🇿', 'スワジランドの旗'),
    Emoji('🇹🇦', 'トリスタンダクーニャの旗'),
    Emoji('🇹🇨', 'タークス・カイコス諸島の旗'),
    Emoji('🇹🇩', 'チャドの旗'),
    Emoji('🇹🇫', 'フランス領南方・南極地域の旗'),
    Emoji('🇹🇬', 'トーゴの旗'),
    Emoji('🇹🇭', 'タイの旗'),
    Emoji('🇹🇯', 'タジキスタンの旗'),
    Emoji('🇹🇰', 'トケラウの旗'),
    Emoji('🇹🇱', '東ティモールの旗'),
    Emoji('🇹🇲', 'トルクメニスタンの旗'),
    Emoji('🇹🇳', 'チュニジアの旗'),
    Emoji('🇹🇴', 'トンガの旗'),
    Emoji('🇹🇷', 'トルコの旗'),
    Emoji('🇹🇹', 'トリニダード・トバゴの旗'),
    Emoji('🇹🇻', 'ツバルの旗'),
    Emoji('🇹🇼', '台湾の旗'),
    Emoji('🇹🇿', 'タンザニアの旗'),
    Emoji('🇺🇦', 'ウクライナの旗'),
    Emoji('🇺🇬', 'ウガンダの旗'),
    Emoji('🇺🇲', 'アメリカ領太平洋諸島の旗'),
    Emoji('🇺🇳', '国連の旗'),
    Emoji('🇺🇸', 'アメリカの旗'),
    Emoji('🇺🇾', 'ウルグアイの旗'),
    Emoji('🇺🇿', 'ウズベキスタンの旗'),
    Emoji('🇻🇦', 'バチカン市国の旗'),
    Emoji('🇻🇨', 'セントビンセント・グレナディーンの旗'),
    Emoji('🇻🇪', 'ベネズエラの旗'),
    Emoji('🇻🇬', 'イギリス領ヴァージン諸島の旗'),
    Emoji('🇻🇮', 'アメリカ領ヴァージン諸島の旗'),
    Emoji('🇻🇳', 'ベトナムの旗'),
    Emoji('🇻🇺', 'バヌアツの旗'),
    Emoji('🇼🇫', 'ウォリス・フツナの旗'),
    Emoji('🇼🇸', 'サモアの旗'),
    Emoji('🇽🇰', 'コソボの旗'),
    Emoji('🇾🇪', 'イエメンの旗'),
    Emoji('🇾🇹', 'マヨットの旗'),
    Emoji('🇿🇦', '南アフリカの旗'),
    Emoji('🇿🇲', 'ザンビアの旗'),
    Emoji('🇿🇼', 'ジンバブエの旗')
  ]),
];
