import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';

/// List of categories of emojis
const List<CategoryEmoji> defaultEmojiSet = [
// ======================================================= Category.SMILEYS
  CategoryEmoji(Category.SMILEYS, [
    Emoji('😀', 'Grinsendes Gesicht'),
    Emoji('😃', 'Grinsendes Gesicht mit großen Augen'),
    Emoji('😄', 'Grinsendes Gesicht mit lächelnden Augen'),
    Emoji('😁', 'Strahlendes Gesicht mit lächelnden Augen'),
    Emoji('😆', 'Grinsendes zusammengekniffenes Gesicht'),
    Emoji('😅', 'Grinsendes Gesicht mit Schweiß'),
    Emoji('🤣', 'Sich vor Lachen auf dem Boden wälzen'),
    Emoji('😂', 'Gesicht mit Freudentränen'),
    Emoji('🙂', 'Leicht lächelndes Gesicht'),
    Emoji('🙃', 'Auf dem Kopf stehendes Gesicht'),
    Emoji('😉', 'Zwinkerndes Gesicht'),
    Emoji('😊', 'Lächelndes Gesicht mit lächelnden Augen'),
    Emoji('😇', 'Lächelndes Gesicht mit Heiligenschein'),
    Emoji('🥰', 'Lächelndes Gesicht mit Herzen'),
    Emoji('😍', 'Lächelndes Gesicht mit Herzaugen'),
    Emoji('🤩', 'Sternenverliebt'),
    Emoji('😘', 'Gesicht, das einen Kuss pustet'),
    Emoji('😗', 'Küssendes Gesicht'),
    Emoji('☺️', 'Lächelndes Gesicht'),
    Emoji('😚', 'Küssendes Gesicht mit geschlossenen Augen'),
    Emoji('😙', 'Küssendes Gesicht mit lächelnden Augen'),
    Emoji('😋', 'Genüsslich essendes Gesicht'),
    Emoji('😛', 'Gesicht mit herausgestreckter Zunge'),
    Emoji('😜', 'Zwinkerndes Gesicht mit herausgestreckter Zunge'),
    Emoji('🤪', 'Verrücktes Gesicht'),
    Emoji('😝', 'Zusammengekniffenes Gesicht mit herausgestreckter Zunge'),
    Emoji('🤑', 'Gesicht mit Geldmund'),
    Emoji('🤗', 'Umarmendes Gesicht'),
    Emoji('🫣', 'Gesicht mit hervorlugendem Auge'),
    Emoji('🤭', 'Gesicht mit Hand vor dem Mund'),
    Emoji('🫢', 'Gesicht mit offenen Augen und Hand vor dem Mund'),
    Emoji('🫡', 'Salutierendes Gesicht'),
    Emoji('🤫', 'Pst-Gesicht'),
    Emoji('🫠', 'Schmelzendes Gesicht'),
    Emoji('🤔', 'Nachdenkliches Gesicht'),
    Emoji('🤐', 'Gesicht mit Reißverschluss-Mund'),
    Emoji('🤨', 'Gesicht mit hochgezogener Augenbraue'),
    Emoji('😐', 'Neutrales Gesicht'),
    Emoji('🫤', 'Gesicht mit schrägem Mund'),
    Emoji('😑', 'Ausdrucksloses Gesicht'),
    Emoji('😶', 'Gesicht ohne Mund'),
    Emoji('🫥', 'Gestricheltes Gesichtsumriss'),
    Emoji('😏', 'Grinsendes Gesicht'),
    Emoji('😒', 'Genervtes Gesicht'),
    Emoji('🙄', 'Gesicht mit rollenden Augen'),
    Emoji('😬', 'Grimassen schneidendes Gesicht'),
    Emoji('🤥', 'Lügendes Gesicht'),
    Emoji('😌', 'Erleichtertes Gesicht'),
    Emoji('😔', 'Nachdenkliches Gesicht'),
    Emoji('🥹', 'Gesicht, das Tränen zurückhält'),
    Emoji('😪', 'Schlafendes Gesicht'),
    Emoji('🤤', 'Sabberndes Gesicht'),
    Emoji('😴', 'Schlafendes Gesicht'),
    Emoji('😷', 'Gesicht mit medizinischer Maske'),
    Emoji('🤒', 'Gesicht mit Thermometer'),
    Emoji('🤕', 'Gesicht mit Kopfverband'),
    Emoji('🤢', 'Übelkeit erregendes Gesicht'),
    Emoji('🤮', 'Erbrechendes Gesicht'),
    Emoji('🤧', 'Niesendes Gesicht'),
    Emoji('🥵', 'Heißes Gesicht'),
    Emoji('🥶', 'Kaltes Gesicht'),
    Emoji('🥴', 'Benommenes Gesicht'),
    Emoji('😵', 'Schwindliges Gesicht'),
    Emoji('🤯', 'Explodierender Kopf'),
    Emoji('🤠', 'Cowboyhut-Gesicht'),
    Emoji('🥳', 'Feierndes Gesicht'),
    Emoji('😎', 'Lächelndes Gesicht mit Sonnenbrille'),
    Emoji('🤓', 'Nerd-Gesicht'),
    Emoji('🧐', 'Gesicht mit Monokel'),
    Emoji('😕', 'Verwirrtes Gesicht'),
    Emoji('😟', 'Besorgtes Gesicht'),
    Emoji('🙁', 'Leicht stirnrunzelndes Gesicht'),
    Emoji('☹️', 'Stirnrunzelndes Gesicht'),
    Emoji('😮', 'Gesicht mit offenem Mund'),
    Emoji('😯', 'Verstummtes Gesicht'),
    Emoji('😲', 'Erstauntes Gesicht'),
    Emoji('😳', 'Errötetes Gesicht'),
    Emoji('🥺', 'Flehendes Gesicht'),
    Emoji('😦', 'Stirnrunzelndes Gesicht mit offenem Mund'),
    Emoji('😧', 'Gequältes Gesicht'),
    Emoji('😨', 'Ängstliches Gesicht'),
    Emoji('😰', 'Ängstliches Gesicht mit Schweiß'),
    Emoji('😥', 'Traurig aber erleichtertes Gesicht'),
    Emoji('😢', 'Weinendes Gesicht'),
    Emoji('😭', 'Laut weinendes Gesicht'),
    Emoji('😱', 'Vor Angst schreiendes Gesicht'),
    Emoji('😖', 'Verwirrtes Gesicht'),
    Emoji('😣', 'Ausharrendes Gesicht'),
    Emoji('😞', 'Enttäuschtes Gesicht'),
    Emoji('😓', 'Niedergeschlagenes Gesicht mit Schweiß'),
    Emoji('😩', 'Erschöpftes Gesicht'),
    Emoji('😫', 'Müdes Gesicht'),
    Emoji('😤', 'Gesicht mit Dampf aus der Nase'),
    Emoji('😡', 'Schmollendes Gesicht'),
    Emoji('😠', 'Wütendes Gesicht'),
    Emoji('🤬', 'Gesicht mit Symbolen auf dem Mund'),
    Emoji('😈', 'Lächelndes Gesicht mit Hörnern'),
    Emoji('👿', 'Wütendes Gesicht mit Hörnern'),
    Emoji('💀', 'Schädel'),
    Emoji('☠️', 'Totenkopf mit gekreuzten Knochen'),
    Emoji('💩', 'Haufen Kot'),
    Emoji('🤡', 'Clown-Gesicht'),
    Emoji('👹', 'Oger'),
    Emoji('👺', 'Kobold'),
    Emoji('👻', 'Geist'),
    Emoji('👽', 'Außerirdischer'),
    Emoji('👾', 'Außerirdisches Monster'),
    Emoji('🤖', 'Robotergesicht'),
    Emoji('🎃', 'Kürbislaterne'),
    Emoji('😺', 'Grinsendes Katzengesicht'),
    Emoji('😸', 'Grinsendes Katzengesicht mit lächelnden Augen'),
    Emoji('😹', 'Katzengesicht mit Freudentränen'),
    Emoji('😻', 'Lächelndes Katzengesicht mit Herzaugen'),
    Emoji('😼', 'Katzengesicht mit schiefem Lächeln'),
    Emoji('😽', 'Küssendes Katzengesicht'),
    Emoji('🙀', 'Erschöpftes Katzengesicht'),
    Emoji('😿', 'Weinendes Katzengesicht'),
    Emoji('😾', 'Schmollendes Katzengesicht'),
    Emoji('🫶', 'Herz-Hände', hasSkinTone: true),
    Emoji('👋', 'Winkende Hand', hasSkinTone: true),
    Emoji('🤚', 'Hochgestreckter Handrücken', hasSkinTone: true),
    Emoji('🖐️', 'Hand mit gespreizten Fingern', hasSkinTone: true),
    Emoji('✋', 'Erhobene Hand', hasSkinTone: true),
    Emoji('🖖', 'Vulcanischer Gruß', hasSkinTone: true),
    Emoji('👌', 'OK-Hand', hasSkinTone: true),
    Emoji('🤌', 'Gezwickte Finger', hasSkinTone: true),
    Emoji('🤏', 'Kneifende Hand', hasSkinTone: true),
    Emoji('🫳', 'Handfläche nach unten', hasSkinTone: true),
    Emoji('🫴', 'Handfläche nach oben', hasSkinTone: true),
    Emoji('✌️', 'Victory-Hand', hasSkinTone: true),
    Emoji('🫰', 'Hand mit gekreuztem Zeigefinger und Daumen',
        hasSkinTone: true),
    Emoji('🤞', 'Gekreuzte Finger', hasSkinTone: true),
    Emoji('🤟', 'Ich liebe dich-Geste', hasSkinTone: true),
    Emoji('🤘', 'Zeichen der Hörner', hasSkinTone: true),
    Emoji('🤙', 'Ruf mich an-Hand', hasSkinTone: true),
    Emoji('👈', 'Nach links zeigender Zeigefinger (Handrücken)',
        hasSkinTone: true),
    Emoji('👉', 'Nach rechts zeigender Zeigefinger (Handrücken)',
        hasSkinTone: true),
    Emoji('👆', 'Nach oben zeigender Zeigefinger (Handrücken)',
        hasSkinTone: true),
    Emoji('🖕', 'Mittelfinger', hasSkinTone: true),
    Emoji('👇', 'Nach unten zeigender Zeigefinger (Handrücken)',
        hasSkinTone: true),
    Emoji('☝️', 'Nach oben zeigender Zeigefinger', hasSkinTone: true),
    Emoji('👍', 'Daumen hoch', hasSkinTone: true),
    Emoji('👎', 'Daumen runter', hasSkinTone: true),
    Emoji('✊', 'Erhobene Faust', hasSkinTone: true),
    Emoji('👊', 'Kommende Faust', hasSkinTone: true),
    Emoji('🤛', 'Nach links gerichtete Faust', hasSkinTone: true),
    Emoji('🤜', 'Nach rechts gerichtete Faust', hasSkinTone: true),
    Emoji('🫲', 'Linke Hand', hasSkinTone: true),
    Emoji('🫱', 'Rechte Hand', hasSkinTone: true),
    Emoji('👏', 'Klatschende Hände', hasSkinTone: true),
    Emoji('🙌', 'Erhobene Hände', hasSkinTone: true),
    Emoji('👐', 'Offene Hände', hasSkinTone: true),
    Emoji('🤲', 'Handflächen zusammen nach oben', hasSkinTone: true),
    Emoji('🤝', 'Händeschütteln', hasSkinTone: true),
    Emoji('🙏', 'Gefaltete Hände', hasSkinTone: true),
    Emoji('🫵', 'Auf den Betrachter zeigender Zeigefinger', hasSkinTone: true),
    Emoji('✍️', 'Schreibende Hand', hasSkinTone: true),
    Emoji('💅', 'Nagellack', hasSkinTone: true),
    Emoji('🤳', 'Selfie', hasSkinTone: true),
    Emoji('💪', 'Angespannter Bizeps', hasSkinTone: true),
    Emoji('🦵', 'Bein', hasSkinTone: true),
    Emoji('🦶', 'Fuß', hasSkinTone: true),
    Emoji('👂', 'Ohr', hasSkinTone: true),
    Emoji('👃', 'Nase', hasSkinTone: true),
    Emoji('🧠', 'Gehirn'),
    Emoji('🦴', 'Knochen'),
    Emoji('👀', 'Augen'),
    Emoji('👁️', 'Auge'),
    Emoji('💋', 'Kussmal'),
    Emoji('👄', 'Mund'),
    Emoji('🫦', 'Auf die Lippe beißen'),
    Emoji('🦷', 'Zahn'),
    Emoji('👅', 'Zunge'),
    Emoji('👶', 'Baby', hasSkinTone: true),
    Emoji('🧒', 'Kind', hasSkinTone: true),
    Emoji('👦', 'Junge', hasSkinTone: true),
    Emoji('👧', 'Mädchen', hasSkinTone: true),
    Emoji('🧑', 'Person', hasSkinTone: true),
    Emoji('👨', 'Mann', hasSkinTone: true),
    Emoji('🧔', 'Mann: Bart', hasSkinTone: true),
    Emoji('👱', 'Mann: blondes Haar', hasSkinTone: true),
    Emoji('👨‍🦰', 'Mann: rotes Haar', hasSkinTone: true),
    Emoji('👨‍🦱', 'Mann: lockiges Haar', hasSkinTone: true),
    Emoji('👨‍🦳', 'Mann: weißes Haar', hasSkinTone: true),
    Emoji('👨‍🦲', 'Mann: Glatze', hasSkinTone: true),
    Emoji('👩', 'Frau', hasSkinTone: true),
    Emoji('👱‍♀️', 'Frau: blondes Haar', hasSkinTone: true),
    Emoji('👩‍🦰', 'Frau: rotes Haar', hasSkinTone: true),
    Emoji('👩‍🦱', 'Frau: lockiges Haar', hasSkinTone: true),
    Emoji('👩‍🦳', 'Frau: weißes Haar', hasSkinTone: true),
    Emoji('👩‍🦲', 'Frau: Glatze', hasSkinTone: true),
    Emoji('🧓', 'Ältere Person', hasSkinTone: true),
    Emoji('👴', 'Alter Mann', hasSkinTone: true),
    Emoji('👵', 'Alte Frau', hasSkinTone: true),
    Emoji('🙍‍♂️', 'Stirnrunzelnder Mann', hasSkinTone: true),
    Emoji('🙍‍♀️', 'Stirnrunzelnde Frau', hasSkinTone: true),
    Emoji('🙎‍♂️', 'Schmollender Mann', hasSkinTone: true),
    Emoji('🙎‍♀️', 'Schmollende Frau', hasSkinTone: true),
    Emoji('🙅‍♂️', 'Nein gestikulierender Mann', hasSkinTone: true),
    Emoji('🙅‍♀️', 'Nein gestikulierende Frau', hasSkinTone: true),
    Emoji('🙆‍♂️', 'OK gestikulierender Mann', hasSkinTone: true),
    Emoji('🙆‍♀️', 'OK gestikulierende Frau', hasSkinTone: true),
    Emoji('💁‍♂️', 'Trinkgeld gebender Mann', hasSkinTone: true),
    Emoji('💁‍♀️', 'Trinkgeld gebende Frau', hasSkinTone: true),
    Emoji('🙋‍♂️', 'Hand hebender Mann', hasSkinTone: true),
    Emoji('🙋‍♀️', 'Hand hebende Frau', hasSkinTone: true),
    Emoji('🙇‍♂️', 'Sich verbeugender Mann', hasSkinTone: true),
    Emoji('🙇‍♀️', 'Sich verbeugende Frau', hasSkinTone: true),
    Emoji('🤦‍♂️', 'Sich an den Kopf fassender Mann', hasSkinTone: true),
    Emoji('🤦‍♀️', 'Sich an den Kopf fassende Frau', hasSkinTone: true),
    Emoji('🤷‍♂️', 'Mit den Schultern zuckender Mann', hasSkinTone: true),
    Emoji('🤷‍♀️', 'Mit den Schultern zuckende Frau', hasSkinTone: true),
    Emoji('👨‍⚕️', 'Männlicher Gesundheitsarbeiter', hasSkinTone: true),
    Emoji('👩‍⚕️', 'Weiblicher Gesundheitsarbeiter', hasSkinTone: true),
    Emoji('👨‍🎓', 'Männlicher Student', hasSkinTone: true),
    Emoji('👩‍🎓', 'Weibliche Studentin', hasSkinTone: true),
    Emoji('👨‍🏫', 'Männlicher Lehrer', hasSkinTone: true),
    Emoji('👩‍🏫', 'Weibliche Lehrerin', hasSkinTone: true),
    Emoji('👨‍⚖️', 'Männlicher Richter', hasSkinTone: true),
    Emoji('👩‍⚖️', 'Weibliche Richterin', hasSkinTone: true),
    Emoji('👨‍🌾', 'Männlicher Bauer', hasSkinTone: true),
    Emoji('👩‍🌾', 'Weibliche Bäuerin', hasSkinTone: true),
    Emoji('👨‍🍳', 'Männlicher Koch', hasSkinTone: true),
    Emoji('👩‍🍳', 'Weiblicher Koch', hasSkinTone: true),
    Emoji('👨‍🔧', 'Männlicher Mechaniker', hasSkinTone: true),
    Emoji('👩‍🔧', 'Weiblicher Mechaniker', hasSkinTone: true),
    Emoji('👨‍🏭', 'Männlicher Fabrikarbeiter', hasSkinTone: true),
    Emoji('👩‍🏭', 'Weiblicher Fabrikarbeiter', hasSkinTone: true),
    Emoji('👨‍💼', 'Männlicher Büroangestellter', hasSkinTone: true),
    Emoji('👩‍💼', 'Weiblicher Büroangestellter', hasSkinTone: true),
    Emoji('👨‍🔬', 'Männlicher Wissenschaftler', hasSkinTone: true),
    Emoji('👩‍🔬', 'Weiblicher Wissenschaftler', hasSkinTone: true),
    Emoji('👨‍💻', 'Männlicher Technologe', hasSkinTone: true),
    Emoji('👩‍💻', 'Weiblicher Technologe', hasSkinTone: true),
    Emoji('👨‍🎤', 'Männlicher Sänger', hasSkinTone: true),
    Emoji('👩‍🎤', 'Weiblicher Sänger', hasSkinTone: true),
    Emoji('👨‍🎨', 'Männlicher Künstler', hasSkinTone: true),
    Emoji('👩‍🎨', 'Weiblicher Künstler', hasSkinTone: true),
    Emoji('👨‍✈️', 'Männlicher Pilot', hasSkinTone: true),
    Emoji('👩‍✈️', 'Weiblicher Pilot', hasSkinTone: true),
    Emoji('👨‍🚀', 'Männlicher Astronaut', hasSkinTone: true),
    Emoji('👩‍🚀', 'Weiblicher Astronaut', hasSkinTone: true),
    Emoji('👨‍🚒', 'Männlicher Feuerwehrmann', hasSkinTone: true),
    Emoji('👩‍🚒', 'Weiblicher Feuerwehrmann', hasSkinTone: true),
    Emoji('👮‍♂️', 'Männlicher Polizist', hasSkinTone: true),
    Emoji('👮‍♀️', 'Weiblicher Polizist', hasSkinTone: true),
    Emoji('🕵️‍♂️', 'Männlicher Detektiv', hasSkinTone: true),
    Emoji('🕵️‍♀️', 'Weiblicher Detektiv', hasSkinTone: true),
    Emoji('💂‍♂️', 'Männlicher Wächter', hasSkinTone: true),
    Emoji('💂‍♀️', 'Weiblicher Wächter', hasSkinTone: true),
    Emoji('👷‍♂️', 'Männlicher Bauarbeiter', hasSkinTone: true),
    Emoji('👷‍♀️', 'Weiblicher Bauarbeiter', hasSkinTone: true),
    Emoji('🤴', 'Prinz', hasSkinTone: true),
    Emoji('👸', 'Prinzessin', hasSkinTone: true),
    Emoji('👳‍♂️', 'Mann mit Turban', hasSkinTone: true),
    Emoji('👳‍♀️', 'Frau mit Turban', hasSkinTone: true),
    Emoji('👲', 'Mann mit chinesischer Kappe', hasSkinTone: true),
    Emoji('🧕', 'Frau mit Kopftuch', hasSkinTone: true),
    Emoji('🤵', 'Mann im Smoking', hasSkinTone: true),
    Emoji('👰', 'Braut mit Schleier', hasSkinTone: true),
    Emoji('🤰', 'Schwangere Frau', hasSkinTone: true),
    Emoji('🤱', 'Stillen', hasSkinTone: true),
    Emoji('👼', 'Babyengel', hasSkinTone: true),
    Emoji('🎅', 'Weihnachtsmann', hasSkinTone: true),
    Emoji('🤶', 'Weihnachtsfrau', hasSkinTone: true),
    Emoji('🦸‍♂️', 'Männlicher Superheld', hasSkinTone: true),
    Emoji('🦸‍♀️', 'Weiblicher Superheld', hasSkinTone: true),
    Emoji('🦹‍♂️', 'Männlicher Superschurke', hasSkinTone: true),
    Emoji('🦹‍♀️', 'Weiblicher Superschurke', hasSkinTone: true),
    Emoji('🧙‍♂️', 'Männlicher Magier', hasSkinTone: true),
    Emoji('🧙‍♀️', 'Weiblicher Magier', hasSkinTone: true),
    Emoji('🧚‍♂️', 'Männliche Fee', hasSkinTone: true),
    Emoji('🧚‍♀️', 'Weibliche Fee', hasSkinTone: true),
    Emoji('🧛‍♂️', 'Männlicher Vampir', hasSkinTone: true),
    Emoji('🧛‍♀️', 'Weiblicher Vampir', hasSkinTone: true),
    Emoji('🧜‍♂️', 'Meermann', hasSkinTone: true),
    Emoji('🧜‍♀️', 'Meerjungfrau', hasSkinTone: true),
    Emoji('🧝‍♂️', 'Männlicher Elf', hasSkinTone: true),
    Emoji('🧝‍♀️', 'Weiblicher Elf', hasSkinTone: true),
    Emoji('🧞‍♂️', 'Männlicher Dschinn'),
    Emoji('🧞‍♀️', 'Weiblicher Dschinn'),
    Emoji('🧟‍♂️', 'Männlicher Zombie'),
    Emoji('🧟‍♀️', 'Weiblicher Zombie'),
    Emoji('💆‍♂️', 'Mann bekommt Massage', hasSkinTone: true),
    Emoji('💆‍♀️', 'Frau bekommt Massage', hasSkinTone: true),
    Emoji('💇‍♂️', 'Mann bekommt Haarschnitt', hasSkinTone: true),
    Emoji('💇‍♀️', 'Frau bekommt Haarschnitt', hasSkinTone: true),
    Emoji('🚶‍♂️', 'Gehender Mann', hasSkinTone: true),
    Emoji('🚶‍♀️', 'Gehende Frau', hasSkinTone: true),
    Emoji('🏃‍♂️', 'Rennender Mann', hasSkinTone: true),
    Emoji('🏃‍♀️', 'Rennende Frau', hasSkinTone: true),
    Emoji('🕺', 'Tanzender Mann', hasSkinTone: true),
    Emoji('💃', 'Tanzende Frau', hasSkinTone: true),
    Emoji('🕴️', 'Schwebender Mann im Anzug', hasSkinTone: true),
    Emoji('👯‍♂️', 'Männer mit Hasenohren'),
    Emoji('👯‍♀️', 'Frauen mit Hasenohren'),
    Emoji('🧖‍♂️', 'Mann im Dampfbad', hasSkinTone: true),
    Emoji('🧖‍♀️', 'Frau im Dampfbad', hasSkinTone: true),
    Emoji('🧘', 'Person im Lotossitz', hasSkinTone: true),
    Emoji('👭', 'Händchenhaltende Frauen', hasSkinTone: true),
    Emoji('👫', 'Händchenhaltende Frau und Mann', hasSkinTone: true),
    Emoji('👬', 'Händchenhaltende Männer', hasSkinTone: true),
    Emoji('💏', 'Kuss'),
    Emoji('👨‍❤️‍💋‍👨', 'Kuss: Mann, Mann'),
    Emoji('👩‍❤️‍💋‍👩', 'Kuss: Frau, Frau'),
    Emoji('💑', 'Paar mit Herz'),
    Emoji('👨‍❤️‍👨', 'Paar mit Herz: Mann, Mann'),
    Emoji('👩‍❤️‍👩', 'Paar mit Herz: Frau, Frau'),
    Emoji('👪', 'Familie'),
    Emoji('👨‍👩‍👦', 'Familie: Mann, Frau, Junge'),
    Emoji('👨‍👩‍👧', 'Familie: Mann, Frau, Mädchen'),
    Emoji('👨‍👩‍👧‍👦', 'Familie: Mann, Frau, Mädchen, Junge'),
    Emoji('👨‍👩‍👦‍👦', 'Familie: Mann, Frau, Junge, Junge'),
    Emoji('👨‍👩‍👧‍👧', 'Familie: Mann, Frau, Mädchen, Mädchen'),
    Emoji('👨‍👨‍👦', 'Familie: Mann, Mann, Junge'),
    Emoji('👨‍👨‍👧', 'Familie: Mann, Mann, Mädchen'),
    Emoji('👨‍👨‍👧‍👦', 'Familie: Mann, Mann, Mädchen, Junge'),
    Emoji('👨‍👨‍👦‍👦', 'Familie: Mann, Mann, Junge, Junge'),
    Emoji('👨‍👨‍👧‍👧', 'Familie: Mann, Mann, Mädchen, Mädchen'),
    Emoji('👩‍👩‍👦', 'Familie: Frau, Frau, Junge'),
    Emoji('👩‍👩‍👧', 'Familie: Frau, Frau, Mädchen'),
    Emoji('👩‍👩‍👧‍👦', 'Familie: Frau, Frau, Mädchen, Junge'),
    Emoji('👩‍👩‍👦‍👦', 'Familie: Frau, Frau, Junge, Junge'),
    Emoji('👩‍👩‍👧‍👧', 'Familie: Frau, Frau, Mädchen, Mädchen'),
    Emoji('👨‍👦', 'Familie: Mann, Junge'),
    Emoji('👨‍👦‍👦', 'Familie: Mann, Junge, Junge'),
    Emoji('👨‍👧', 'Familie: Mann, Mädchen'),
    Emoji('👨‍👧‍👦', 'Familie: Mann, Mädchen, Junge'),
    Emoji('👨‍👧‍👧', 'Familie: Mann, Mädchen, Mädchen'),
    Emoji('👩‍👦', 'Familie: Frau, Junge'),
    Emoji('👩‍👦‍👦', 'Familie: Frau, Junge, Junge'),
    Emoji('👩‍👧', 'Familie: Frau, Mädchen'),
    Emoji('👩‍👧‍👦', 'Familie: Frau, Mädchen, Junge'),
    Emoji('👩‍👧‍👧', 'Familie: Frau, Mädchen, Mädchen'),
    Emoji('🗣️', 'Sprechende Kopf'),
    Emoji('👤', 'Büste in Silhouette'),
    Emoji('👥', 'Büsten in Silhouette'),
    Emoji('🫂', 'Umarmende Menschen'),
    Emoji('👣', 'Fußabdrücke'),
    Emoji('🧳', 'Gepäck'),
    Emoji('🌂', 'Geschlossener Regenschirm'),
    Emoji('☂️', 'Regenschirm'),
    Emoji('🧵', 'Faden'),
    Emoji('🧶', 'Garn'),
    Emoji('👓', 'Brille'),
    Emoji('🕶️', 'Sonnenbrille'),
    Emoji('🥽', 'Schutzbrille'),
    Emoji('🥼', 'Laborkittel'),
    Emoji('👔', 'Krawatte'),
    Emoji('👕', 'T-Shirt'),
    Emoji('👖', 'Jeans'),
    Emoji('🧣', 'Schal'),
    Emoji('🧤', 'Handschuhe'),
    Emoji('🧥', 'Mantel'),
    Emoji('🧦', 'Socken'),
    Emoji('👗', 'Kleid'),
    Emoji('👘', 'Kimono'),
    Emoji('👙', 'Bikini'),
    Emoji('👚', 'Damenkleidung'),
    Emoji('👛', 'Geldbeutel'),
    Emoji('👜', 'Handtasche'),
    Emoji('👝', 'Clutch'),
    Emoji('🎒', 'Rucksack'),
    Emoji('👞', 'Herrenschuh'),
    Emoji('👟', 'Laufschuh'),
    Emoji('🥾', 'Wanderschuh'),
    Emoji('🥿', 'Flacher Schuh'),
    Emoji('👠', 'High Heels'),
    Emoji('👡', 'Damensandale'),
    Emoji('👢', 'Damenstiefel'),
    Emoji('👑', 'Krone'),
    Emoji('👒', 'Damenhut'),
    Emoji('🎩', 'Zylinder'),
    Emoji('🎓', 'Abschlusskappe'),
    Emoji('🧢', 'Baseballkappe'),
    Emoji('⛑️', 'Helm des Rettungssanitäters'),
    Emoji('💄', 'Lippenstift'),
    Emoji('💍', 'Ring'),
    Emoji('💼', 'Aktentasche')
  ]),

// ======================================================= Category.ANIMALS
  CategoryEmoji(Category.ANIMALS, [
    Emoji('🐶', 'Hundegesicht'),
    Emoji('🐱', 'Katzengesicht'),
    Emoji('🐭', 'Mausgesicht'),
    Emoji('🐹', 'Hamstergesicht'),
    Emoji('🐰', 'Hasengesicht'),
    Emoji('🦊', 'Fuchsgesicht'),
    Emoji('🐻', 'Bärengesicht'),
    Emoji('🐼', 'Pandagesicht'),
    Emoji('🐨', 'Koalagesicht'),
    Emoji('🐯', 'Tigergesicht'),
    Emoji('🦁', 'Löwengesicht'),
    Emoji('🐮', 'Kuhgesicht'),
    Emoji('🐷', 'Schweinegesicht'),
    Emoji('🐽', 'Schweinenase'),
    Emoji('🐸', 'Froschgesicht'),
    Emoji('🐵', 'Affengesicht'),
    Emoji('🙈', 'Nichts-böses-Affe'),
    Emoji('🙉', 'Nichts-hörendes-Affe'),
    Emoji('🙊', 'Nichts-sagendes-Affe'),
    Emoji('🐒', 'Affe'),
    Emoji('💥', 'Kollision'),
    Emoji('💫', 'Schwindel'),
    Emoji('💦', 'Schweißtropfen'),
    Emoji('💨', 'Davoneilen'),
    Emoji('🦍', 'Gorilla'),
    Emoji('🐕', 'Hund'),
    Emoji('🐩', 'Pudel'),
    Emoji('🐺', 'Wolfsgesicht'),
    Emoji('🦝', 'Waschbär'),
    Emoji('🐈', 'Katze'),
    Emoji('🐅', 'Tiger'),
    Emoji('🐆', 'Leopard'),
    Emoji('🐴', 'Pferdegesicht'),
    Emoji('🐎', 'Pferd'),
    Emoji('🦄', 'Einhorn'),
    Emoji('🦓', 'Zebra'),
    Emoji('🐂', 'Ochse'),
    Emoji('🐃', 'Wasserbüffel'),
    Emoji('🐄', 'Kuh'),
    Emoji('🐖', 'Schwein'),
    Emoji('🐗', 'Wildschwein'),
    Emoji('🐏', 'Widder'),
    Emoji('🐑', 'Mutterschaf'),
    Emoji('🐐', 'Ziege'),
    Emoji('🐪', 'Kamel'),
    Emoji('🐫', 'Zweihöckriges Kamel'),
    Emoji('🦙', 'Lama'),
    Emoji('🦒', 'Giraffe'),
    Emoji('🐘', 'Elefant'),
    Emoji('🦏', 'Nashorn'),
    Emoji('🦛', 'Nilpferd'),
    Emoji('🐁', 'Maus'),
    Emoji('🐀', 'Ratte'),
    Emoji('🐇', 'Hase'),
    Emoji('🐿️', 'Streifenhörnchen'),
    Emoji('🦔', 'Igel'),
    Emoji('🦇', 'Fledermaus'),
    Emoji('🦘', 'Känguru'),
    Emoji('🦡', 'Dachs'),
    Emoji('🐾', 'Pfotenabdrücke'),
    Emoji('🦃', 'Truthahn'),
    Emoji('🐔', 'Huhn'),
    Emoji('🐓', 'Hahn'),
    Emoji('🐣', 'Schlüpfendes Küken'),
    Emoji('🐤', 'Küken'),
    Emoji('🐥', 'Küken von vorn'),
    Emoji('🐦', 'Vogel'),
    Emoji('🐧', 'Pinguin'),
    Emoji('🕊️', 'Taube'),
    Emoji('🦅', 'Adler'),
    Emoji('🦆', 'Ente'),
    Emoji('🦢', 'Schwan'),
    Emoji('🦉', 'Eule'),
    Emoji('🦚', 'Pfau'),
    Emoji('🦜', 'Papagei'),
    Emoji('🐊', 'Krokodil'),
    Emoji('🐢', 'Schildkröte'),
    Emoji('🦎', 'Eidechse'),
    Emoji('🐍', 'Schlange'),
    Emoji('🐲', 'Drachengesicht'),
    Emoji('🐉', 'Drache'),
    Emoji('🦕', 'Sauropode'),
    Emoji('🦖', 'T-Rex'),
    Emoji('🧌', 'Troll'),
    Emoji('🐳', 'Spritzender Wal'),
    Emoji('🐋', 'Wal'),
    Emoji('🐬', 'Delfin'),
    Emoji('🐟', 'Fisch'),
    Emoji('🐠', 'Tropischer Fisch'),
    Emoji('🐡', 'Kugelfisch'),
    Emoji('🦈', 'Hai'),
    Emoji('🐙', 'Oktopus'),
    Emoji('🪹', 'Leeres Nest'),
    Emoji('🪺', 'Nest mit Eiern'),
    Emoji('🐚', 'Spiralförmige Muschel'),
    Emoji('🪸', 'Koralle'),
    Emoji('🐌', 'Schnecke'),
    Emoji('🦋', 'Schmetterling'),
    Emoji('🐛', 'Raupe'),
    Emoji('🐜', 'Ameise'),
    Emoji('🐝', 'Honigbiene'),
    Emoji('🐞', 'Marienkäfer'),
    Emoji('🦗', 'Grille'),
    Emoji('🕷️', 'Spinne'),
    Emoji('🕸️', 'Spinnennetz'),
    Emoji('🦂', 'Skorpion'),
    Emoji('🦟', 'Moskito'),
    Emoji('🦠', 'Mikrobe'),
    Emoji('💐', 'Blumenstrauß'),
    Emoji('🌸', 'Kirschblüte'),
    Emoji('💮', 'Weiße Blume'),
    Emoji('🏵️', 'Rosette'),
    Emoji('🪷', 'Lotus'),
    Emoji('🌹', 'Rose'),
    Emoji('🥀', 'Verwelkte Blume'),
    Emoji('🌺', 'Hibiskus'),
    Emoji('🌻', 'Sonnenblume'),
    Emoji('🌼', 'Blüte'),
    Emoji('🌷', 'Tulpe'),
    Emoji('🌱', 'Keimling'),
    Emoji('🌲', 'Immergrüner Baum'),
    Emoji('🌳', 'Laubbaum'),
    Emoji('🌴', 'Palme'),
    Emoji('🌵', 'Kaktus'),
    Emoji('🌾', 'Reisgarbe'),
    Emoji('🌿', 'Kraut'),
    Emoji('☘️', 'Kleeblatt'),
    Emoji('🍀', 'Vierblättriges Kleeblatt'),
    Emoji('🍁', 'Ahornblatt'),
    Emoji('🍂', 'Herbstlaub'),
    Emoji('🍃', 'Im Wind flatterndes Blatt'),
    Emoji('🍄', 'Pilz'),
    Emoji('🌰', 'Kastanie'),
    Emoji('🦀', 'Krabbe'),
    Emoji('🦞', 'Hummer'),
    Emoji('🦐', 'Garnele'),
    Emoji('🦑', 'Tintenfisch'),
    Emoji('🌍', 'Globus: Europa-Afrika'),
    Emoji('🌎', 'Globus: Amerika'),
    Emoji('🌏', 'Globus: Asien-Australien'),
    Emoji('🌐', 'Globus mit Meridianen'),
    Emoji('🌑', 'Neumond'),
    Emoji('🌒', 'Zunehmende Sichel'),
    Emoji('🌓', 'Erstes Viertel'),
    Emoji('🌔', 'Zunehmender Halbmond'),
    Emoji('🌕', 'Vollmond'),
    Emoji('🌖', 'Abnehmender Halbmond'),
    Emoji('🌗', 'Letztes Viertel'),
    Emoji('🌘', 'Abnehmende Sichel'),
    Emoji('🌙', 'Sichelmond'),
    Emoji('🌚', 'Neumondgesicht'),
    Emoji('🌛', 'Gesicht des ersten Viertels'),
    Emoji('🌜', 'Gesicht des letzten Viertels'),
    Emoji('☀️', 'Sonne'),
    Emoji('🌝', 'Vollmondgesicht'),
    Emoji('🌞', 'Sonne mit Gesicht'),
    Emoji('⭐', 'Stern'),
    Emoji('🌟', 'Leuchtender Stern'),
    Emoji('🌠', 'Sternschnuppe'),
    Emoji('☁️', 'Wolke'),
    Emoji('⛅', 'Sonne hinter Wolke'),
    Emoji('⛈️', 'Wolke mit Blitz und Regen'),
    Emoji('🌤️', 'Sonne hinter kleiner Wolke'),
    Emoji('🌥️', 'Sonne hinter großer Wolke'),
    Emoji('🌦️', 'Sonne hinter Regenwolke'),
    Emoji('🌧️', 'Wolke mit Regen'),
    Emoji('🌨️', 'Wolke mit Schnee'),
    Emoji('🌩️', 'Wolke mit Blitz'),
    Emoji('🌪️', 'Tornado'),
    Emoji('🌫️', 'Nebel'),
    Emoji('🌬️', 'Windgesicht'),
    Emoji('🌈', 'Regenbogen'),
    Emoji('☂️', 'Regenschirm'),
    Emoji('☔', 'Regenschirm mit Regentropfen'),
    Emoji('⚡', 'Hochspannung'),
    Emoji('❄️', 'Schneeflocke'),
    Emoji('☃️', 'Schneemann'),
    Emoji('⛄', 'Schneemann ohne Schnee'),
    Emoji('☄️', 'Komet'),
    Emoji('🔥', 'Feuer'),
    Emoji('💧', 'Tropfen'),
    Emoji('🫧', 'Blasen'),
    Emoji('🌊', 'Wasserwelle'),
    Emoji('🎄', 'Weihnachtsbaum'),
    Emoji('✨', 'Glitzer'),
    Emoji('🎋', 'Tanabata-Baum'),
    Emoji('🎍', 'Kiefernschmuck')
  ]),

// ======================================================= Category.FOODS
  CategoryEmoji(Category.FOODS, [
    Emoji('🍇', 'Trauben'),
    Emoji('🍈', 'Melone'),
    Emoji('🍉', 'Wassermelone'),
    Emoji('🍊', 'Mandarine'),
    Emoji('🍋', 'Zitrone'),
    Emoji('🍌', 'Banane'),
    Emoji('🍍', 'Ananas'),
    Emoji('🥭', 'Mango'),
    Emoji('🍎', 'Roter Apfel'),
    Emoji('🍏', 'Grüner Apfel'),
    Emoji('🍐', 'Birne'),
    Emoji('🍑', 'Pfirsich'),
    Emoji('🍒', 'Kirschen'),
    Emoji('🍓', 'Erdbeere'),
    Emoji('🥝', 'Kiwi'),
    Emoji('🍅', 'Tomate'),
    Emoji('🥥', 'Kokosnuss'),
    Emoji('🥑', 'Avocado'),
    Emoji('🍆', 'Aubergine'),
    Emoji('🥔', 'Kartoffel'),
    Emoji('🥕', 'Karotte'),
    Emoji('🌽', 'Maiskolben'),
    Emoji('🌶️', 'Chilischote'),
    Emoji('🥒', 'Gurke'),
    Emoji('🥬', 'Blattgrün'),
    Emoji('🥦', 'Brokkoli'),
    Emoji('🍄', 'Pilz'),
    Emoji('🥜', 'Erdnüsse'),
    Emoji('🫘', 'Bohnen'),
    Emoji('🌰', 'Kastanie'),
    Emoji('🍞', 'Brot'),
    Emoji('🥐', 'Croissant'),
    Emoji('🥖', 'Baguette'),
    Emoji('🥨', 'Brezel'),
    Emoji('🥯', 'Bagel'),
    Emoji('🥞', 'Pfannkuchen'),
    Emoji('🧀', 'Käseecke'),
    Emoji('🍖', 'Fleisch am Knochen'),
    Emoji('🍗', 'Geflügelkeule'),
    Emoji('🥩', 'Fleischstück'),
    Emoji('🥓', 'Speck'),
    Emoji('🍔', 'Hamburger'),
    Emoji('🍟', 'Pommes frites'),
    Emoji('🍕', 'Pizza'),
    Emoji('🌭', 'Hotdog'),
    Emoji('🥪', 'Sandwich'),
    Emoji('🌮', 'Taco'),
    Emoji('🌯', 'Burrito'),
    Emoji('🥙', 'Gefülltes Fladenbrot'),
    Emoji('🍳', 'Kochen'),
    Emoji('🥘', 'Flache Pfanne mit Essen'),
    Emoji('🍲', 'Topf mit Essen'),
    Emoji('🥣', 'Schüssel mit Löffel'),
    Emoji('🥗', 'Grüner Salat'),
    Emoji('🍿', 'Popcorn'),
    Emoji('🧂', 'Salz'),
    Emoji('🥫', 'Dosenfutter'),
    Emoji('🫙', 'Glas'),
    Emoji('🍱', 'Bento-Box'),
    Emoji('🍘', 'Reiscracker'),
    Emoji('🍙', 'Reisbällchen'),
    Emoji('🍚', 'Gekochter Reis'),
    Emoji('🍛', 'Curryreis'),
    Emoji('🍜', 'Dampfende Schüssel'),
    Emoji('🍝', 'Spaghetti'),
    Emoji('🍠', 'Geröstete Süßkartoffel'),
    Emoji('🍢', 'Oden'),
    Emoji('🍣', 'Sushi'),
    Emoji('🍤', 'Gebratene Garnelen'),
    Emoji('🍥', 'Fischkuchen mit Spirale'),
    Emoji('🥮', 'Mondkuchen'),
    Emoji('🍡', 'Dango'),
    Emoji('🥟', 'Teigtasche'),
    Emoji('🥠', 'Glückskeks'),
    Emoji('🥡', 'Takeout-Box'),
    Emoji('🍦', 'Softeis'),
    Emoji('🍧', 'Eisraspeln'),
    Emoji('🍨', 'Eiscreme'),
    Emoji('🍩', 'Donut'),
    Emoji('🍪', 'Keks'),
    Emoji('🎂', 'Geburtstagskuchen'),
    Emoji('🍰', 'Törtchen'),
    Emoji('🧁', 'Cupcake'),
    Emoji('🥧', 'Kuchen'),
    Emoji('🍫', 'Schokoladentafel'),
    Emoji('🍬', 'Süßigkeit'),
    Emoji('🍭', 'Lutscher'),
    Emoji('🍮', 'Pudding'),
    Emoji('🍯', 'Honigtopf'),
    Emoji('🍼', 'Babyflasche'),
    Emoji('🥛', 'Glas Milch'),
    Emoji('🫗', 'Flüssigkeit gießen'),
    Emoji('☕', 'Heißgetränk'),
    Emoji('🍵', 'Teetasse ohne Henkel'),
    Emoji('🧉', 'Mate-Getränk'),
    Emoji('🍶', 'Sake'),
    Emoji('🍾', 'Flasche mit knallendem Korken'),
    Emoji('🍷', 'Weinglas'),
    Emoji('🍸', 'Cocktailglas'),
    Emoji('🍹', 'Tropisches Getränk'),
    Emoji('🍺', 'Bierkrug'),
    Emoji('🍻', 'Anstoßende Bierkrüge'),
    Emoji('🥂', 'Anstoßende Gläser'),
    Emoji('🥃', 'Tumbler-Glas'),
    Emoji('🥤', 'Becher mit Strohhalm'),
    Emoji('🥢', 'Essstäbchen'),
    Emoji('🍽️', 'Gabel und Messer mit Teller'),
    Emoji('🍴', 'Gabel und Messer'),
    Emoji('🥄', 'Löffel')
  ]),

// ======================================================= Category.TRAVEL
  CategoryEmoji(Category.TRAVEL, [
    Emoji('🗾', 'Karte von Japan'),
    Emoji('🏔️', 'Schneebedeckter Berg'),
    Emoji('⛰️', 'Berg'),
    Emoji('🌋', 'Vulkan'),
    Emoji('🗻', 'Mount Fuji'),
    Emoji('🏕️', 'Camping'),
    Emoji('🏖️', 'Strand mit Sonnenschirm'),
    Emoji('🏜️', 'Wüste'),
    Emoji('🏝️', 'Einsame Insel'),
    Emoji('🏞️', 'Nationalpark'),
    Emoji('🏟️', 'Stadion'),
    Emoji('🏛️', 'Klassisches Gebäude'),
    Emoji('🏗️', 'Gebäude im Bau'),
    Emoji('🏘️', 'Häuser'),
    Emoji('🏚️', 'Verfallenes Haus'),
    Emoji('🏠', 'Haus'),
    Emoji('🏡', 'Haus mit Garten'),
    Emoji('🏢', 'Bürogebäude'),
    Emoji('🏣', 'Japanisches Postamt'),
    Emoji('🏤', 'Postamt'),
    Emoji('🏥', 'Krankenhaus'),
    Emoji('🏦', 'Bank'),
    Emoji('🏨', 'Hotel'),
    Emoji('🏩', 'Liebeshotel'),
    Emoji('🏪', 'Convenience Store'),
    Emoji('🏫', 'Schule'),
    Emoji('🏬', 'Kaufhaus'),
    Emoji('🏭', 'Fabrik'),
    Emoji('🏯', 'Japanische Burg'),
    Emoji('🏰', 'Burg'),
    Emoji('💒', 'Hochzeit'),
    Emoji('🗼', 'Tokyo Tower'),
    Emoji('🗽', 'Freiheitsstatue'),
    Emoji('⛪', 'Kirche'),
    Emoji('🕌', 'Moschee'),
    Emoji('🕍', 'Synagoge'),
    Emoji('⛩️', 'Shinto-Schrein'),
    Emoji('🕋', 'Kaaba'),
    Emoji('⛲', 'Brunnen'),
    Emoji('⛺', 'Zelt'),
    Emoji('🌁', 'Neblig'),
    Emoji('🌃', 'Nacht mit Sternen'),
    Emoji('🏙️', 'Stadtbild'),
    Emoji('🌄', 'Sonnenaufgang über den Bergen'),
    Emoji('🌅', 'Sonnenaufgang'),
    Emoji('🌆', 'Stadtbild in der Abenddämmerung'),
    Emoji('🌇', 'Sonnenuntergang'),
    Emoji('🌉', 'Brücke bei Nacht'),
    Emoji('🎠', 'Karussellpferd'),
    Emoji('🎡', 'Riesenrad'),
    Emoji('🎢', 'Achterbahn'),
    Emoji('🚂', 'Lokomotive'),
    Emoji('🚃', 'Eisenbahnwaggon'),
    Emoji('🚄', 'Hochgeschwindigkeitszug'),
    Emoji('🚅', 'Hochgeschwindigkeitszug'),
    Emoji('🚆', 'Zug'),
    Emoji('🚇', 'U-Bahn'),
    Emoji('🚈', 'Stadtbahn'),
    Emoji('🚉', 'Bahnhof'),
    Emoji('🚊', 'Straßenbahn'),
    Emoji('🚝', 'Einschienenbahn'),
    Emoji('🚞', 'Bergbahn'),
    Emoji('🚋', 'Straßenbahnwaggon'),
    Emoji('🚌', 'Bus'),
    Emoji('🚍', 'Entgegenkommender Bus'),
    Emoji('🚎', 'Oberleitungsbus'),
    Emoji('🚐', 'Minibus'),
    Emoji('🚑', 'Krankenwagen'),
    Emoji('🚒', 'Feuerwehrauto'),
    Emoji('🚓', 'Polizeiauto'),
    Emoji('🚔', 'Entgegenkommendes Polizeiauto'),
    Emoji('🚕', 'Taxi'),
    Emoji('🚖', 'Entgegenkommendes Taxi'),
    Emoji('🚗', 'Auto'),
    Emoji('🚘', 'Entgegenkommendes Auto'),
    Emoji('🚚', 'Lieferwagen'),
    Emoji('🚛', 'Sattelschlepper'),
    Emoji('🚜', 'Traktor'),
    Emoji('🏎️', 'Rennwagen'),
    Emoji('🏍️', 'Motorrad'),
    Emoji('🛵', 'Motorroller'),
    Emoji('🚲', 'Fahrrad'),
    Emoji('🛴', 'Tretroller'),
    Emoji('🚏', 'Bushaltestelle'),
    Emoji('🛤️', 'Eisenbahngleise'),
    Emoji('⛽', 'Tankstelle'),
    Emoji('🛞', 'Rad'),
    Emoji('🚨', 'Blinklicht des Polizeiautos'),
    Emoji('🚥', 'Horizontale Ampel'),
    Emoji('🚦', 'Vertikale Ampel'),
    Emoji('🚧', 'Baustelle'),
    Emoji('⚓', 'Anker'),
    Emoji('⛵', 'Segelboot'),
    Emoji('🚤', 'Schnellboot'),
    Emoji('🛳️', 'Passagierschiff'),
    Emoji('⛴️', 'Fähre'),
    Emoji('🛥️', 'Motorboot'),
    Emoji('🚢', 'Schiff'),
    Emoji('🛟', 'Rettungsring'),
    Emoji('✈️', 'Flugzeug'),
    Emoji('🛩️', 'Kleines Flugzeug'),
    Emoji('🛫', 'Flugzeugabflug'),
    Emoji('🛬', 'Flugzeugankunft'),
    Emoji('💺', 'Sitz'),
    Emoji('🚁', 'Hubschrauber'),
    Emoji('🚟', 'Hängebahn'),
    Emoji('🚠', 'Bergbahn'),
    Emoji('🚡', 'Seilbahn'),
    Emoji('🛰️', 'Satellit'),
    Emoji('🚀', 'Rakete'),
    Emoji('🛸', 'Fliegende Untertasse'),
    Emoji('🌠', 'Sternschnuppe'),
    Emoji('🌌', 'Milchstraße'),
    Emoji('⛱️', 'Sonnenschirm am Boden'),
    Emoji('🎆', 'Feuerwerk'),
    Emoji('🎇', 'Wunderkerze'),
    Emoji('🎑', 'Mondbetrachtungszeremonie'),
    Emoji('🗿', 'Moai'),
    Emoji('🛂', 'Passkontrolle'),
    Emoji('🛃', 'Zoll'),
    Emoji('🛄', 'Gepäckausgabe'),
    Emoji('🛅', 'Gepäckaufbewahrung')
  ]),

// ======================================================= Category.ACTIVITIES
  CategoryEmoji(Category.ACTIVITIES, [
    Emoji('🧗‍♂️', 'Kletternder Mann', hasSkinTone: true),
    Emoji('🧗‍♀️', 'Kletternde Frau', hasSkinTone: true),
    Emoji('🏇', 'Pferderennen', hasSkinTone: true),
    Emoji('⛷️', 'Skier'),
    Emoji('🏂', 'Snowboarder'),
    Emoji('🏌️‍♂️', 'Golfspielender Mann', hasSkinTone: true),
    Emoji('🏌️‍♀️', 'Golfspielende Frau', hasSkinTone: true),
    Emoji('🏄‍♂️', 'Surfender Mann', hasSkinTone: true),
    Emoji('🏄‍♀️', 'Surfende Frau', hasSkinTone: true),
    Emoji('🚣‍♂️', 'Rudernder Mann', hasSkinTone: true),
    Emoji('🚣‍♀️', 'Rudernde Frau', hasSkinTone: true),
    Emoji('🏊‍♂️', 'Schwimmender Mann', hasSkinTone: true),
    Emoji('🏊‍♀️', 'Schwimmende Frau', hasSkinTone: true),
    Emoji('⛹️‍♂️', 'Mann mit prellendem Ball', hasSkinTone: true),
    Emoji('⛹️‍♀️', 'Frau mit prellendem Ball', hasSkinTone: true),
    Emoji('🏋️‍♂️', 'Gewichthebender Mann', hasSkinTone: true),
    Emoji('🏋️‍♀️', 'Gewichthebende Frau', hasSkinTone: true),
    Emoji('🚴‍♂️', 'Radfahrender Mann', hasSkinTone: true),
    Emoji('🚴‍♀️', 'Radfahrende Frau', hasSkinTone: true),
    Emoji('🚵‍♂️', 'Mountainbikender Mann', hasSkinTone: true),
    Emoji('🚵‍♀️', 'Mountainbikende Frau', hasSkinTone: true),
    Emoji('🤸‍♂️', 'Radschlagender Mann', hasSkinTone: true),
    Emoji('🤸‍♀️', 'Radschlagende Frau', hasSkinTone: true),
    Emoji('🤼‍♂️', 'Ringende Männer', hasSkinTone: true),
    Emoji('🤼‍♀️', 'Ringende Frauen', hasSkinTone: true),
    Emoji('🤽‍♂️', 'Wasserballspielender Mann', hasSkinTone: true),
    Emoji('🤽‍♀️', 'Wasserballspielende Frau', hasSkinTone: true),
    Emoji('🤾‍♂️', 'Handballspielender Mann', hasSkinTone: true),
    Emoji('🤾‍♀️', 'Handballspielende Frau', hasSkinTone: true),
    Emoji('🤹‍♂️', 'Jonglierender Mann', hasSkinTone: true),
    Emoji('🤹‍♀️', 'Jonglierende Frau', hasSkinTone: true),
    Emoji('🧘‍♂️', 'Mann im Lotossitz', hasSkinTone: true),
    Emoji('🧘‍♀️', 'Frau im Lotossitz', hasSkinTone: true),
    Emoji('🎪', 'Zirkuszelt'),
    Emoji('🛹', 'Skateboard'),
    Emoji('🎗️', 'Erinnerungsband'),
    Emoji('🎟️', 'Eintrittskarten'),
    Emoji('🎫', 'Ticket'),
    Emoji('🎖️', 'Militärmedaille'),
    Emoji('🏆', 'Pokal'),
    Emoji('🏅', 'Sportmedaille'),
    Emoji('🥇', 'Goldmedaille'),
    Emoji('🥈', 'Silbermedaille'),
    Emoji('🥉', 'Bronzemedaille'),
    Emoji('⚽', 'Fußball'),
    Emoji('⚾', 'Baseball'),
    Emoji('🥎', 'Softball'),
    Emoji('🏀', 'Basketball'),
    Emoji('🏐', 'Volleyball'),
    Emoji('🏈', 'American Football'),
    Emoji('🏉', 'Rugbyball'),
    Emoji('🎾', 'Tennis'),
    Emoji('🥏', 'Frisbeescheibe'),
    Emoji('🎳', 'Bowling'),
    Emoji('🏏', 'Cricket'),
    Emoji('🏑', 'Feldhockey'),
    Emoji('🏒', 'Eishockey'),
    Emoji('🥍', 'Lacrosse'),
    Emoji('🏓', 'Tischtennis'),
    Emoji('🏸', 'Federball'),
    Emoji('🪃', 'Bumerang'),
    Emoji('🥅', 'Tornetz'),
    Emoji('⛳', 'Fahne im Loch'),
    Emoji('🪁', 'Drachen'),
    Emoji('🛝', 'Rutsche'),
    Emoji('🏹', 'Pfeil und Bogen'),
    Emoji('🎣', 'Angelrute'),
    Emoji('🤿', 'Tauchermaske'),
    Emoji('🥊', 'Boxhandschuh'),
    Emoji('🥋', 'Kampfsportuniform'),
    Emoji('🎽', 'Laufshirt'),
    Emoji('🛼', 'Rollschuhe'),
    Emoji('🛷', 'Schlitten'),
    Emoji('⛸️', 'Schlittschuhe'),
    Emoji('🥌', 'Curlingstein'),
    Emoji('🎿', 'Ski'),
    Emoji('🎯', 'Volltreffer'),
    Emoji('🎱', 'Billardkugel 8'),
    Emoji('🎮', 'Videospiel'),
    Emoji('🎰', 'Spielautomat'),
    Emoji('🎲', 'Spielwürfel'),
    Emoji('🧩', 'Puzzle'),
    Emoji('♟️', 'Schachbauer'),
    Emoji('🎭', 'Darstellende Kunst'),
    Emoji('🎨', 'Palette'),
    Emoji('🧵', 'Faden'),
    Emoji('🧶', 'Garn'),
    Emoji('🎼', 'Partitur'),
    Emoji('🎤', 'Mikrofon'),
    Emoji('🎧', 'Kopfhörer'),
    Emoji('🎷', 'Saxophon'),
    Emoji('🎸', 'Gitarre'),
    Emoji('🎹', 'Keyboard'),
    Emoji('🎺', 'Trompete'),
    Emoji('🎻', 'Violine'),
    Emoji('🥁', 'Trommel'),
    Emoji('🎬', 'Klappe')
  ]),

// ======================================================= Category.OBJECTS
  CategoryEmoji(Category.OBJECTS, [
    Emoji('💌', 'Liebesbrief'),
    Emoji('🕳️', 'Loch'),
    Emoji('💣', 'Bombe'),
    Emoji('🛀', 'Person beim Baden'),
    Emoji('🛌', 'Person im Bett'),
    Emoji('🏺', 'Amphore'),
    Emoji('🗺️', 'Weltkarte'),
    Emoji('🧭', 'Kompass'),
    Emoji('🧱', 'Ziegelstein'),
    Emoji('💈', 'Barberpole'),
    Emoji('🛢️', 'Ölfass'),
    Emoji('🛎️', 'Hotelglocke'),
    Emoji('🧳', 'Gepäck'),
    Emoji('⌛', 'Abgelaufene Sanduhr'),
    Emoji('⏳', 'Laufende Sanduhr'),
    Emoji('⌚', 'Armbanduhr'),
    Emoji('⏰', 'Wecker'),
    Emoji('⏱️', 'Stoppuhr'),
    Emoji('⏲️', 'Zeitschaltuhr'),
    Emoji('🕰️', 'Kaminuhr'),
    Emoji('🌡️', 'Thermometer'),
    Emoji('⛱️', 'Sonnenschirm am Boden'),
    Emoji('🧨', 'Feuerwerkskörper'),
    Emoji('🎈', 'Luftballon'),
    Emoji('🎉', 'Partyknaller'),
    Emoji('🎊', 'Konfettiball'),
    Emoji('🎎', 'Japanische Puppen'),
    Emoji('🎏', 'Karpfenfahne'),
    Emoji('🎐', 'Windspiel'),
    Emoji('🪩', 'Diskokugel'),
    Emoji('🧧', 'Roter Umschlag'),
    Emoji('🎀', 'Schleife'),
    Emoji('🎁', 'Eingepacktes Geschenk'),
    Emoji('🔮', 'Kristallkugel'),
    Emoji('🧿', 'Nazar-Amulett'),
    Emoji('🪬', 'Hamsa'),
    Emoji('🕹️', 'Joystick'),
    Emoji('🧸', 'Teddybär'),
    Emoji('🖼️', 'Gerahmtes Bild'),
    Emoji('🧵', 'Faden'),
    Emoji('🧶', 'Garn'),
    Emoji('🛍️', 'Einkaufstaschen'),
    Emoji('📿', 'Gebetskette'),
    Emoji('💎', 'Edelstein'),
    Emoji('📯', 'Posthorn'),
    Emoji('🎙️', 'Studiomikrofon'),
    Emoji('🎚️', 'Schieberegler'),
    Emoji('🎛️', 'Regler'),
    Emoji('📻', 'Radio'),
    Emoji('📱', 'Handy'),
    Emoji('📲', 'Handy mit Pfeil'),
    Emoji('☎️', 'Telefon'),
    Emoji('📞', 'Telefonhörer'),
    Emoji('📟', 'Pager'),
    Emoji('📠', 'Faxgerät'),
    Emoji('🔋', 'Batterie'),
    Emoji('🪫', 'Schwache Batterie'),
    Emoji('🔌', 'Stecker'),
    Emoji('💻', 'Laptop'),
    Emoji('🖥️', 'Desktop-Computer'),
    Emoji('🖨️', 'Drucker'),
    Emoji('⌨️', 'Tastatur'),
    Emoji('🖱️', 'Computermaus'),
    Emoji('🖲️', 'Trackball'),
    Emoji('💽', 'Computerdiskette'),
    Emoji('💾', 'Diskette'),
    Emoji('💿', 'Optische Disk'),
    Emoji('📀', 'DVD'),
    Emoji('🧮', 'Abakus'),
    Emoji('🎥', 'Filmkamera'),
    Emoji('🎞️', 'Filmbilder'),
    Emoji('📽️', 'Filmprojektor'),
    Emoji('📺', 'Fernseher'),
    Emoji('📷', 'Kamera'),
    Emoji('📸', 'Kamera mit Blitz'),
    Emoji('📹', 'Videokamera'),
    Emoji('📼', 'Videokassette'),
    Emoji('🔍', 'Lupe nach links geneigt'),
    Emoji('🔎', 'Lupe nach rechts geneigt'),
    Emoji('🕯️', 'Kerze'),
    Emoji('💡', 'Glühbirne'),
    Emoji('🔦', 'Taschenlampe'),
    Emoji('🏮', 'Rote Papierlaterne'),
    Emoji('📔', 'Notizbuch mit dekorativem Einband'),
    Emoji('📕', 'Geschlossenes Buch'),
    Emoji('📖', 'Offenes Buch'),
    Emoji('📗', 'Grünes Buch'),
    Emoji('📘', 'Blaues Buch'),
    Emoji('📙', 'Orangefarbenes Buch'),
    Emoji('📚', 'Bücher'),
    Emoji('📓', 'Notizbuch'),
    Emoji('📃', 'Seite mit Curl'),
    Emoji('📜', 'Schriftrolle'),
    Emoji('📄', 'Seite nach oben'),
    Emoji('📰', 'Zeitung'),
    Emoji('🗞️', 'Zusammengerollte Zeitung'),
    Emoji('📑', 'Lesezeichen'),
    Emoji('🔖', 'Lesezeichen'),
    Emoji('🏷️', 'Etikett'),
    Emoji('💰', 'Geldsack'),
    Emoji('💴', 'Yen-Banknote'),
    Emoji('💵', 'Dollar-Banknote'),
    Emoji('💶', 'Euro-Banknote'),
    Emoji('💷', 'Pfund-Banknote'),
    Emoji('💸', 'Geld mit Flügeln'),
    Emoji('💳', 'Kreditkarte'),
    Emoji('🪪', 'Ausweis'),
    Emoji('🧾', 'Quittung'),
    Emoji('✉️', 'Umschlag'),
    Emoji('📧', 'E-Mail'),
    Emoji('📨', 'Eingehender Umschlag'),
    Emoji('📩', 'Umschlag mit Pfeil'),
    Emoji('📤', 'Postausgang'),
    Emoji('📥', 'Posteingang'),
    Emoji('📦', 'Paket'),
    Emoji('📫', 'Geschlossener Briefkasten mit erhobener Flagge'),
    Emoji('📪', 'Geschlossener Briefkasten mit gesenkter Flagge'),
    Emoji('📬', 'Offener Briefkasten mit erhobener Flagge'),
    Emoji('📭', 'Offener Briefkasten mit gesenkter Flagge'),
    Emoji('📮', 'Briefkasten'),
    Emoji('🗳️', 'Wahlurne mit Stimmzettel'),
    Emoji('✏️', 'Bleistift'),
    Emoji('✒️', 'Schwarze Feder'),
    Emoji('🖋️', 'Füllfederhalter'),
    Emoji('🖊️', 'Stift'),
    Emoji('🖌️', 'Pinsel'),
    Emoji('🖍️', 'Buntstift'),
    Emoji('📝', 'Memo'),
    Emoji('📁', 'Ordner'),
    Emoji('📂', 'Geöffneter Ordner'),
    Emoji('🗂️', 'Karteikartentrenner'),
    Emoji('📅', 'Kalender'),
    Emoji('📆', 'Abreißkalender'),
    Emoji('🗒️', 'Spiralblock'),
    Emoji('🗓️', 'Spiralkalender'),
    Emoji('📇', 'Kartei'),
    Emoji('📈', 'Steigendes Diagramm'),
    Emoji('📉', 'Fallendes Diagramm'),
    Emoji('📊', 'Balkendiagramm'),
    Emoji('📋', 'Klemmbrett'),
    Emoji('📌', 'Reißzwecke'),
    Emoji('📍', 'Runde Reißzwecke'),
    Emoji('📎', 'Büroklammer'),
    Emoji('🖇️', 'Verbundene Büroklammern'),
    Emoji('📏', 'Lineal'),
    Emoji('📐', 'Geodreieck'),
    Emoji('✂️', 'Schere'),
    Emoji('🗃️', 'Karteikasten'),
    Emoji('🗄️', 'Aktenschrank'),
    Emoji('🗑️', 'Papierkorb'),
    Emoji('🔒', 'Verschlossen'),
    Emoji('🔓', 'Entsperrt'),
    Emoji('🔏', 'Verschlossen mit Stift'),
    Emoji('🔐', 'Verschlossen mit Schlüssel'),
    Emoji('🔑', 'Schlüssel'),
    Emoji('🗝️', 'Alter Schlüssel'),
    Emoji('🔨', 'Hammer'),
    Emoji('⛏️', 'Spitzhacke'),
    Emoji('⚒️', 'Hammer und Spitzhacke'),
    Emoji('🛠️', 'Hammer und Schraubenschlüssel'),
    Emoji('🔪', 'Küchenmesser'),
    Emoji('🗡️', 'Dolch'),
    Emoji('⚔️', 'Gekreuzte Schwerter'),
    Emoji('🔫', 'Pistole'),
    Emoji('🛡️', 'Schild'),
    Emoji('🔧', 'Schraubenschlüssel'),
    Emoji('🔩', 'Mutter und Schraube'),
    Emoji('⚙️', 'Zahnrad'),
    Emoji('🗜️', 'Schraubzwinge'),
    Emoji('⚖️', 'Waage'),
    Emoji('🔗', 'Link'),
    Emoji('⛓️', 'Ketten'),
    Emoji('🧰', 'Werkzeugkasten'),
    Emoji('🧲', 'Magnet'),
    Emoji('⚗️', 'Destillierkolben'),
    Emoji('🧪', 'Reagenzglas'),
    Emoji('🧫', 'Petrischale'),
    Emoji('🧬', 'DNA'),
    Emoji('🔬', 'Mikroskop'),
    Emoji('🩻', 'Röntgenbild'),
    Emoji('🔭', 'Teleskop'),
    Emoji('📡', 'Satellitenschüssel'),
    Emoji('💉', 'Spritze'),
    Emoji('💊', 'Pille'),
    Emoji('🚪', 'Tür'),
    Emoji('🛏️', 'Bett'),
    Emoji('🛋️', 'Sofa und Lampe'),
    Emoji('🚽', 'Toilette'),
    Emoji('🚿', 'Dusche'),
    Emoji('🛁', 'Badewanne'),
    Emoji('🧴', 'Lotionflasche'),
    Emoji('🧷', 'Sicherheitsnadel'),
    Emoji('🧹', 'Besen'),
    Emoji('🧺', 'Korb'),
    Emoji('🧻', 'Rolle Toilettenpapier'),
    Emoji('🧼', 'Seife'),
    Emoji('🧽', 'Schwamm'),
    Emoji('🧯', 'Feuerlöscher'),
    Emoji('🚬', 'Zigarette'),
    Emoji('⚰️', 'Sarg'),
    Emoji('⚱️', 'Urne'),
    Emoji('🚰', 'Trinkwasser')
  ]),

// ======================================================= Category.SYMBOLS
  CategoryEmoji(Category.SYMBOLS, [
    Emoji('💘', 'Herz mit Pfeil'),
    Emoji('💝', 'Herz mit Schleife'),
    Emoji('💖', 'Funkelndes Herz'),
    Emoji('💗', 'Wachsendes Herz'),
    Emoji('💓', 'Schlagendes Herz'),
    Emoji('💞', 'Sich drehende Herzen'),
    Emoji('💕', 'Zwei Herzen'),
    Emoji('💟', 'Herzverzierung'),
    Emoji('❣️', 'Starkes Herz-Ausrufezeichen'),
    Emoji('💔', 'Gebrochenes Herz'),
    Emoji('❤️', 'Rotes Herz'),
    Emoji('🧡', 'Orangefarbenes Herz'),
    Emoji('💛', 'Gelbes Herz'),
    Emoji('💚', 'Grünes Herz'),
    Emoji('💙', 'Blaues Herz'),
    Emoji('💜', 'Lila Herz'),
    Emoji('🖤', 'Schwarzes Herz'),
    Emoji('💯', 'Hundert Punkte'),
    Emoji('💢', 'Wutsmbol'),
    Emoji('💬', 'Sprechblase'),
    Emoji('👁️‍🗨️', 'Auge in Sprechblase'),
    Emoji('🗯️', 'Rechte Wutblase'),
    Emoji('💭', 'Gedankenblase'),
    Emoji('💤', 'Zzz'),
    Emoji('💮', 'Weiße Blume'),
    Emoji('♨️', 'Heiße Quellen'),
    Emoji('💈', 'Barberpole'),
    Emoji('🛑', 'Stoppschild'),
    Emoji('🕛', 'Zwölf Uhr'),
    Emoji('🕧', 'Zwölf Uhr dreißig'),
    Emoji('🕐', 'Ein Uhr'),
    Emoji('🕜', 'Ein Uhr dreißig'),
    Emoji('🕑', 'Zwei Uhr'),
    Emoji('🕝', 'Zwei Uhr dreißig'),
    Emoji('🕒', 'Drei Uhr'),
    Emoji('🕞', 'Drei Uhr dreißig'),
    Emoji('🕓', 'Vier Uhr'),
    Emoji('🕟', 'Vier Uhr dreißig'),
    Emoji('🕔', 'Fünf Uhr'),
    Emoji('🕠', 'Fünf Uhr dreißig'),
    Emoji('🕕', 'Sechs Uhr'),
    Emoji('🕡', 'Sechs Uhr dreißig'),
    Emoji('🕖', 'Sieben Uhr'),
    Emoji('🕢', 'Sieben Uhr dreißig'),
    Emoji('🕗', 'Acht Uhr'),
    Emoji('🕣', 'Acht Uhr dreißig'),
    Emoji('🕘', 'Neun Uhr'),
    Emoji('🕤', 'Neun Uhr dreißig'),
    Emoji('🕙', 'Zehn Uhr'),
    Emoji('🕥', 'Zehn Uhr dreißig'),
    Emoji('🕚', 'Elf Uhr'),
    Emoji('🕦', 'Elf Uhr dreißig'),
    Emoji('🌀', 'Zyklon'),
    Emoji('♠️', 'Pik'),
    Emoji('♥️', 'Herz'),
    Emoji('♦️', 'Karo'),
    Emoji('♣️', 'Kreuz'),
    Emoji('🃏', 'Joker'),
    Emoji('🀄', 'Mahjong Roter Drache'),
    Emoji('🎴', 'Blumenspielkarten'),
    Emoji('🔇', 'Stummgeschalteter Lautsprecher'),
    Emoji('🔈', 'Lautsprecher geringe Lautstärke'),
    Emoji('🔉', 'Lautsprecher mittlere Lautstärke'),
    Emoji('🔊', 'Lautsprecher hohe Lautstärke'),
    Emoji('📢', 'Lautsprecher'),
    Emoji('📣', 'Megaphon'),
    Emoji('📯', 'Posthorn'),
    Emoji('🔔', 'Glocke'),
    Emoji('🔕', 'Glocke mit Schrägstrich'),
    Emoji('🎵', 'Musiknote'),
    Emoji('🎶', 'Musiknoten'),
    Emoji('🏧', 'Geldautomaten-Schild'),
    Emoji('🚮', 'Abfall-im-Mülleimer-Schild'),
    Emoji('🚰', 'Trinkwasser'),
    Emoji('♿', 'Rollstuhlsymbol'),
    Emoji('🩼', 'Krücke'),
    Emoji('🚹', 'Herrentoilette'),
    Emoji('🚺', 'Damentoilette'),
    Emoji('🚻', 'Toilette'),
    Emoji('🚼', 'Babysymbol'),
    Emoji('🚾', 'WC'),
    Emoji('⚠️', 'Warnung'),
    Emoji('🚸', 'Kinderüberweg'),
    Emoji('⛔', 'Einfahrt verboten'),
    Emoji('🚫', 'Verboten'),
    Emoji('🚳', 'Fahrradfahren verboten'),
    Emoji('🚭', 'Rauchen verboten'),
    Emoji('🚯', 'Nicht wegwerfen'),
    Emoji('🚱', 'Kein Trinkwasser'),
    Emoji('🚷', 'Fußgänger verboten'),
    Emoji('🔞', 'Keine Personen unter achtzehn'),
    Emoji('☢️', 'Radioaktiv'),
    Emoji('☣️', 'Biogefährdung'),
    Emoji('⬆️', 'Pfeil nach oben'),
    Emoji('↗️', 'Pfeil nach oben rechts'),
    Emoji('➡️', 'Pfeil nach rechts'),
    Emoji('↘️', 'Pfeil nach unten rechts'),
    Emoji('⬇️', 'Pfeil nach unten'),
    Emoji('↙️', 'Pfeil nach unten links'),
    Emoji('⬅️', 'Pfeil nach links'),
    Emoji('↖️', 'Pfeil nach oben links'),
    Emoji('↕️', 'Pfeil nach oben und unten'),
    Emoji('↔️', 'Pfeil nach links und rechts'),
    Emoji('↩️', 'Pfeil nach rechts gebogen links'),
    Emoji('↪️', 'Pfeil nach links gebogen rechts'),
    Emoji('⤴️', 'Pfeil nach rechts gebogen oben'),
    Emoji('⤵️', 'Pfeil nach rechts gebogen unten'),
    Emoji('🔃', 'Im Uhrzeigersinn verlaufende vertikale Pfeile'),
    Emoji('🔄', 'Gegen den Uhrzeigersinn verlaufende Pfeile'),
    Emoji('🔙', 'Zurück-Pfeil'),
    Emoji('🔚', 'Ende-Pfeil'),
    Emoji('🔛', 'An!-Pfeil'),
    Emoji('🔜', 'Bald-Pfeil'),
    Emoji('🔝', 'Oben-Pfeil'),
    Emoji('🛐', 'Gebetsstätte'),
    Emoji('⚛️', 'Atomsymbol'),
    Emoji('🕉️', 'Om'),
    Emoji('✡️', 'Davidstern'),
    Emoji('☸️', 'Rad des Dharma'),
    Emoji('☯️', 'Yin Yang'),
    Emoji('✝️', 'Lateinisches Kreuz'),
    Emoji('☦️', 'Orthodoxes Kreuz'),
    Emoji('☪️', 'Stern und Halbmond'),
    Emoji('☮️', 'Friedenssymbol'),
    Emoji('🕎', 'Menora'),
    Emoji('🔯', 'Gepunkteter sechszackiger Stern'),
    Emoji('♈', 'Widder'),
    Emoji('♉', 'Stier'),
    Emoji('♊', 'Zwillinge'),
    Emoji('♋', 'Krebs'),
    Emoji('♌', 'Löwe'),
    Emoji('♍', 'Jungfrau'),
    Emoji('♎', 'Waage'),
    Emoji('♏', 'Skorpion'),
    Emoji('♐', 'Schütze'),
    Emoji('♑', 'Steinbock'),
    Emoji('♒', 'Wassermann'),
    Emoji('♓', 'Fische'),
    Emoji('⛎', 'Schlangenträger'),
    Emoji('🔀', 'Shuffle-Tracks-Button'),
    Emoji('🔁', 'Wiederholen-Button'),
    Emoji('🔂', 'Einzelwiederholung-Button'),
    Emoji('▶️', 'Play-Button'),
    Emoji('⏩', 'Vorspulen-Button'),
    Emoji('◀️', 'Zurückspulen-Button'),
    Emoji('⏪', 'Schnellrücklauf-Button'),
    Emoji('🔼', 'Nach-oben-Button'),
    Emoji('⏫', 'Schnell-nach-oben-Button'),
    Emoji('🔽', 'Nach-unten-Button'),
    Emoji('⏬', 'Schnell-nach-unten-Button'),
    Emoji('⏹️', 'Stopp-Button'),
    Emoji('⏏️', 'Auswerfen-Button'),
    Emoji('🎦', 'Kino'),
    Emoji('🔅', 'Dimmen-Button'),
    Emoji('🔆', 'Heller-Button'),
    Emoji('📶', 'Antennenbalken'),
    Emoji('📳', 'Vibrationsmodus'),
    Emoji('📴', 'Handy aus'),
    Emoji('♾️', 'Unendlich'),
    Emoji('♻️', 'Recyclingsymbol'),
    Emoji('🔱', 'Dreizack-Emblem'),
    Emoji('📛', 'Namensschild'),
    Emoji('🔰', 'Japanisches Symbol für Anfänger'),
    Emoji('⭕', 'Dicker großer Kreis'),
    Emoji('✅', 'Dicker weißer Haken'),
    Emoji('☑️', 'Wahlurne mit Haken'),
    Emoji('✔️', 'Dicker Haken'),
    Emoji('❌', 'Kreuz'),
    Emoji('❎', 'Kreuz-Button'),
    Emoji('➕', 'Dickes Pluszeichen'),
    Emoji('➖', 'Dickes Minuszeichen'),
    Emoji('➗', 'Dickes Geteiltzeichen'),
    Emoji('✖️', 'Dickes Multiplikationszeichen X'),
    Emoji('🟰', 'Dickes Gleichheitszeichen'),
    Emoji('➰', 'Geschweifte Schleife'),
    Emoji('➿', 'Doppelte geschweifte Schleife'),
    Emoji('〽️', 'Teilwechselzeichen'),
    Emoji('✳️', 'Achtstrahliges Sternchen'),
    Emoji('✴️', 'Achtzackiger Stern'),
    Emoji('❇️', 'Funkeln'),
    Emoji('‼️', 'Doppeltes Ausrufezeichen'),
    Emoji('⁉️', 'Ausrufe-Fragezeichen'),
    Emoji('❓', 'Fragezeichen'),
    Emoji('❔', 'Weißes Fragezeichen'),
    Emoji('❕', 'Weißes Ausrufezeichen'),
    Emoji('❗', 'Ausrufezeichen'),
    Emoji('©️', 'Copyright'),
    Emoji('®️', 'Registriert'),
    Emoji('™️', 'Warenzeichen'),
    Emoji('#️⃣', 'Raute-Taste'),
    Emoji('0️⃣', 'Zifferntaste Null'),
    Emoji('1️⃣', 'Zifferntaste Eins'),
    Emoji('2️⃣', 'Zifferntaste Zwei'),
    Emoji('3️⃣', 'Zifferntaste Drei'),
    Emoji('4️⃣', 'Zifferntaste Vier'),
    Emoji('5️⃣', 'Zifferntaste Fünf'),
    Emoji('6️⃣', 'Zifferntaste Sechs'),
    Emoji('7️⃣', 'Zifferntaste Sieben'),
    Emoji('8️⃣', 'Zifferntaste Acht'),
    Emoji('9️⃣', 'Zifferntaste Neun'),
    Emoji('🔟', 'Zifferntaste 10'),
    Emoji('🔠', 'Eingabe Lateinische Großbuchstaben'),
    Emoji('🔡', 'Eingabe Lateinische Kleinbuchstaben'),
    Emoji('🔢', 'Eingabe Zahlen'),
    Emoji('🔣', 'Eingabe Symbole'),
    Emoji('🔤', 'Eingabe Lateinische Buchstaben'),
    Emoji('🅰️', 'A-Taste (Blutgruppe)'),
    Emoji('🆎', 'AB-Taste (Blutgruppe)'),
    Emoji('🅱️', 'B-Taste (Blutgruppe)'),
    Emoji('🆑', 'CL-Taste'),
    Emoji('🆒', 'Cool-Taste'),
    Emoji('🆓', 'Gratis-Taste'),
    Emoji('ℹ️', 'Information'),
    Emoji('🆔', 'ID-Taste'),
    Emoji('Ⓜ️', 'Eingekreistes M'),
    Emoji('🆕', 'Neu-Taste'),
    Emoji('🆖', 'NG-Taste'),
    Emoji('🅾️', 'O-Taste (Blutgruppe)'),
    Emoji('🆗', 'OK-Taste'),
    Emoji('🅿️', 'P-Taste'),
    Emoji('🆘', 'SOS-Taste'),
    Emoji('🆙', 'Hoch!-Taste'),
    Emoji('🆚', 'Vs-Taste'),
    Emoji('🈁', 'Japanische „Hier“-Taste'),
    Emoji('🈂️', 'Japanische „Servicegebühr“-Taste'),
    Emoji('🈷️', 'Japanische „Monatsbetrag“-Taste'),
    Emoji('🈶', 'Japanische „Nicht kostenlos“-Taste'),
    Emoji('🈯', 'Japanische „Reserviert“-Taste'),
    Emoji('🉐', 'Japanische „Schnäppchen“-Taste'),
    Emoji('🈹', 'Japanische „Rabatt“-Taste'),
    Emoji('🈚', 'Japanische „Kostenlos“-Taste'),
    Emoji('🈲', 'Japanische „Verboten“-Taste'),
    Emoji('🉑', 'Japanische „Akzeptabel“-Taste'),
    Emoji('🈸', 'Japanische „Anwendung“-Taste'),
    Emoji('🈴', 'Japanische „Bestanden“-Taste'),
    Emoji('🈳', 'Japanische „Frei“-Taste'),
    Emoji('㊗️', 'Japanische „Glückwunsch“-Taste'),
    Emoji('㊙️', 'Japanische „Geheimnis“-Taste'),
    Emoji('🈺', 'Japanische „Geöffnet“-Taste'),
    Emoji('🈵', 'Japanische „Kein Platz“-Taste'),
    Emoji('🔴', 'Roter Kreis'),
    Emoji('🔵', 'Blauer Kreis'),
    Emoji('⚫', 'Schwarzer Kreis'),
    Emoji('⚪', 'Weißer Kreis'),
    Emoji('⬛', 'Schwarzes großes Quadrat'),
    Emoji('⬜', 'Weißes großes Quadrat'),
    Emoji('◼️', 'Schwarzes mittleres Quadrat'),
    Emoji('◻️', 'Weißes mittleres Quadrat'),
    Emoji('◾', 'Schwarzes mittelkleines Quadrat'),
    Emoji('◽', 'Weißes mittelkleines Quadrat'),
    Emoji('▪️', 'Schwarzes kleines Quadrat'),
    Emoji('▫️', 'Weißes kleines Quadrat'),
    Emoji('🔶', 'Große orangefarbene Raute'),
    Emoji('🔷', 'Große blaue Raute'),
    Emoji('🔸', 'Kleine orangefarbene Raute'),
    Emoji('🔹', 'Kleine blaue Raute'),
    Emoji('🔺', 'Rotes Dreieck nach oben'),
    Emoji('🔻', 'Rotes Dreieck nach unten'),
    Emoji('💠', 'Raute mit Punkt'),
    Emoji('🔳', 'Weißer quadratischer Button'),
    Emoji('🔲', 'Schwarzer quadratischer Button')
  ]),

// ======================================================= Category.FLAGS
  CategoryEmoji(Category.FLAGS, [
    Emoji('🏁', 'Karierte Flagge'),
    Emoji('🚩', 'Dreieckige Flagge'),
    Emoji('🎌', 'Gekreuzte Flaggen'),
    Emoji('🏴', 'Schwarze Flagge'),
    Emoji('🏳️', 'Weiße Flagge'),
    Emoji('🏳️‍🌈', 'Regenbogenflagge'),
    Emoji('🏳️‍⚧️', 'Transgender-Flagge'),
    Emoji('🏴‍☠️', 'Piratenflagge'),
    Emoji('🇦🇨', 'Flagge: Ascension'),
    Emoji('🇦🇩', 'Flagge: Andorra'),
    Emoji('🇦🇪', 'Flagge: Vereinigte Arabische Emirate'),
    Emoji('🇦🇫', 'Flagge: Afghanistan'),
    Emoji('🇦🇬', 'Flagge: Antigua und Barbuda'),
    Emoji('🇦🇮', 'Flagge: Anguilla'),
    Emoji('🇦🇱', 'Flagge: Albanien'),
    Emoji('🇦🇲', 'Flagge: Armenien'),
    Emoji('🇦🇴', 'Flagge: Angola'),
    Emoji('🇦🇶', 'Flagge: Antarktis'),
    Emoji('🇦🇷', 'Flagge: Argentinien'),
    Emoji('🇦🇸', 'Flagge: Amerikanisch-Samoa'),
    Emoji('🇦🇹', 'Flagge: Österreich'),
    Emoji('🇦🇺', 'Flagge: Australien'),
    Emoji('🇦🇼', 'Flagge: Aruba'),
    Emoji('🇦🇽', 'Flagge: Ålandinseln'),
    Emoji('🇦🇿', 'Flagge: Aserbaidschan'),
    Emoji('🇧🇦', 'Flagge: Bosnien und Herzegowina'),
    Emoji('🇧🇧', 'Flagge: Barbados'),
    Emoji('🇧🇩', 'Flagge: Bangladesch'),
    Emoji('🇧🇪', 'Flagge: Belgien'),
    Emoji('🇧🇫', 'Flagge: Burkina Faso'),
    Emoji('🇧🇬', 'Flagge: Bulgarien'),
    Emoji('🇧🇭', 'Flagge: Bahrain'),
    Emoji('🇧🇮', 'Flagge: Burundi'),
    Emoji('🇧🇯', 'Flagge: Benin'),
    Emoji('🇧🇱', 'Flagge: Saint-Barthélemy'),
    Emoji('🇧🇲', 'Flagge: Bermuda'),
    Emoji('🇧🇳', 'Flagge: Brunei'),
    Emoji('🇧🇴', 'Flagge: Bolivien'),
    Emoji('🇧🇶', 'Flagge: Karibische Niederlande'),
    Emoji('🇧🇷', 'Flagge: Brasilien'),
    Emoji('🇧🇸', 'Flagge: Bahamas'),
    Emoji('🇧🇹', 'Flagge: Bhutan'),
    Emoji('🇧🇻', 'Flagge: Bouvetinsel'),
    Emoji('🇧🇼', 'Flagge: Botsuana'),
    Emoji('🇧🇾', 'Flagge: Belarus'),
    Emoji('🇧🇿', 'Flagge: Belize'),
    Emoji('🇨🇦', 'Flagge: Kanada'),
    Emoji('🇨🇨', 'Flagge: Kokosinseln'),
    Emoji('🇨🇩', 'Flagge: Kongo-Kinshasa'),
    Emoji('🇨🇫', 'Flagge: Zentralafrikanische Republik'),
    Emoji('🇨🇬', 'Flagge: Kongo-Brazzaville'),
    Emoji('🇨🇭', 'Flagge: Schweiz'),
    Emoji('🇨🇮', 'Flagge: Elfenbeinküste'),
    Emoji('🇨🇰', 'Flagge: Cookinseln'),
    Emoji('🇨🇱', 'Flagge: Chile'),
    Emoji('🇨🇲', 'Flagge: Kamerun'),
    Emoji('🇨🇳', 'Flagge: China'),
    Emoji('🇨🇴', 'Flagge: Kolumbien'),
    Emoji('🇨🇵', 'Flagge: Clipperton-Insel'),
    Emoji('🇨🇷', 'Flagge: Costa Rica'),
    Emoji('🇨🇺', 'Flagge: Kuba'),
    Emoji('🇨🇻', 'Flagge: Kap Verde'),
    Emoji('🇨🇼', 'Flagge: Curaçao'),
    Emoji('🇨🇽', 'Flagge: Weihnachtsinsel'),
    Emoji('🇨🇾', 'Flagge: Zypern'),
    Emoji('🇨🇿', 'Flagge: Tschechien'),
    Emoji('🇩🇪', 'Flagge: Deutschland'),
    Emoji('🇩🇬', 'Flagge: Diego Garcia'),
    Emoji('🇩🇯', 'Flagge: Dschibuti'),
    Emoji('🇩🇰', 'Flagge: Dänemark'),
    Emoji('🇩🇲', 'Flagge: Dominica'),
    Emoji('🇩🇴', 'Flagge: Dominikanische Republik'),
    Emoji('🇩🇿', 'Flagge: Algerien'),
    Emoji('🇪🇦', 'Flagge: Ceuta und Melilla'),
    Emoji('🇪🇨', 'Flagge: Ecuador'),
    Emoji('🇪🇪', 'Flagge: Estland'),
    Emoji('🇪🇬', 'Flagge: Ägypten'),
    Emoji('🇪🇭', 'Flagge: Westsahara'),
    Emoji('🇪🇷', 'Flagge: Eritrea'),
    Emoji('🇪🇸', 'Flagge: Spanien'),
    Emoji('🇪🇹', 'Flagge: Äthiopien'),
    Emoji('🇪🇺', 'Flagge: Europäische Union'),
    Emoji('🇫🇮', 'Flagge: Finnland'),
    Emoji('🇫🇯', 'Flagge: Fidschi'),
    Emoji('🇫🇰', 'Flagge: Falklandinseln'),
    Emoji('🇫🇲', 'Flagge: Mikronesien'),
    Emoji('🇫🇴', 'Flagge: Färöer'),
    Emoji('🇫🇷', 'Flagge: Frankreich'),
    Emoji('🇬🇦', 'Flagge: Gabun'),
    Emoji('🇬🇧', 'Flagge: Vereinigtes Königreich'),
    Emoji('🇬🇩', 'Flagge: Grenada'),
    Emoji('🇬🇪', 'Flagge: Georgien'),
    Emoji('🇬🇫', 'Flagge: Französisch-Guayana'),
    Emoji('🇬🇬', 'Flagge: Guernsey'),
    Emoji('🇬🇭', 'Flagge: Ghana'),
    Emoji('🇬🇮', 'Flagge: Gibraltar'),
    Emoji('🇬🇱', 'Flagge: Grönland'),
    Emoji('🇬🇲', 'Flagge: Gambia'),
    Emoji('🇬🇳', 'Flagge: Guinea'),
    Emoji('🇬🇵', 'Flagge: Guadeloupe'),
    Emoji('🇬🇶', 'Flagge: Äquatorialguinea'),
    Emoji('🇬🇷', 'Flagge: Griechenland'),
    Emoji('🇬🇸', 'Flagge: Südgeorgien und die Südlichen Sandwichinseln'),
    Emoji('🇬🇹', 'Flagge: Guatemala'),
    Emoji('🇬🇺', 'Flagge: Guam'),
    Emoji('🇬🇼', 'Flagge: Guinea-Bissau'),
    Emoji('🇬🇾', 'Flagge: Guyana'),
    Emoji('🇭🇰', 'Flagge: Hongkong'),
    Emoji('🇭🇲', 'Flagge: Heard und McDonaldinseln'),
    Emoji('🇭🇳', 'Flagge: Honduras'),
    Emoji('🇭🇷', 'Flagge: Kroatien'),
    Emoji('🇭🇹', 'Flagge: Haiti'),
    Emoji('🇭🇺', 'Flagge: Ungarn'),
    Emoji('🇮🇨', 'Flagge: Kanarische Inseln'),
    Emoji('🇮🇩', 'Flagge: Indonesien'),
    Emoji('🇮🇪', 'Flagge: Irland'),
    Emoji('🇮🇱', 'Flagge: Israel'),
    Emoji('🇮🇲', 'Flagge: Isle of Man'),
    Emoji('🇮🇳', 'Flagge: Indien'),
    Emoji('🇮🇴', 'Flagge: Britisches Territorium im Indischen Ozean'),
    Emoji('🇮🇶', 'Flagge: Irak'),
    Emoji('🇮🇷', 'Flagge: Iran'),
    Emoji('🇮🇸', 'Flagge: Island'),
    Emoji('🇮🇹', 'Flagge: Italien'),
    Emoji('🇯🇪', 'Flagge: Jersey'),
    Emoji('🇯🇲', 'Flagge: Jamaika'),
    Emoji('🇯🇴', 'Flagge: Jordanien'),
    Emoji('🇯🇵', 'Flagge: Japan'),
    Emoji('🇰🇪', 'Flagge: Kenia'),
    Emoji('🇰🇬', 'Flagge: Kirgisistan'),
    Emoji('🇰🇭', 'Flagge: Kambodscha'),
    Emoji('🇰🇮', 'Flagge: Kiribati'),
    Emoji('🇰🇲', 'Flagge: Komoren'),
    Emoji('🇰🇳', 'Flagge: St. Kitts und Nevis'),
    Emoji('🇰🇵', 'Flagge: Nordkorea'),
    Emoji('🇰🇷', 'Flagge: Südkorea'),
    Emoji('🇰🇼', 'Flagge: Kuwait'),
    Emoji('🇰🇾', 'Flagge: Kaimaninseln'),
    Emoji('🇰🇿', 'Flagge: Kasachstan'),
    Emoji('🇱🇦', 'Flagge: Laos'),
    Emoji('🇱🇧', 'Flagge: Libanon'),
    Emoji('🇱🇨', 'Flagge: St. Lucia'),
    Emoji('🇱🇮', 'Flagge: Liechtenstein'),
    Emoji('🇱🇰', 'Flagge: Sri Lanka'),
    Emoji('🇱🇷', 'Flagge: Liberia'),
    Emoji('🇱🇸', 'Flagge: Lesotho'),
    Emoji('🇱🇹', 'Flagge: Litauen'),
    Emoji('🇱🇺', 'Flagge: Luxemburg'),
    Emoji('🇱🇻', 'Flagge: Lettland'),
    Emoji('🇱🇾', 'Flagge: Libyen'),
    Emoji('🇲🇦', 'Flagge: Marokko'),
    Emoji('🇲🇨', 'Flagge: Monaco'),
    Emoji('🇲🇩', 'Flagge: Moldau'),
    Emoji('🇲🇪', 'Flagge: Montenegro'),
    Emoji('🇲🇫', 'Flagge: St. Martin'),
    Emoji('🇲🇬', 'Flagge: Madagaskar'),
    Emoji('🇲🇭', 'Flagge: Marshallinseln'),
    Emoji('🇲🇰', 'Flagge: Nordmazedonien'),
    Emoji('🇲🇱', 'Flagge: Mali'),
    Emoji('🇲🇲', 'Flagge: Myanmar'),
    Emoji('🇲🇳', 'Flagge: Mongolei'),
    Emoji('🇲🇴', 'Flagge: Macau'),
    Emoji('🇲🇵', 'Flagge: Nördliche Marianen'),
    Emoji('🇲🇶', 'Flagge: Martinique'),
    Emoji('🇲🇷', 'Flagge: Mauretanien'),
    Emoji('🇲🇸', 'Flagge: Montserrat'),
    Emoji('🇲🇹', 'Flagge: Malta'),
    Emoji('🇲🇺', 'Flagge: Mauritius'),
    Emoji('🇲🇻', 'Flagge: Malediven'),
    Emoji('🇲🇼', 'Flagge: Malawi'),
    Emoji('🇲🇽', 'Flagge: Mexiko'),
    Emoji('🇲🇾', 'Flagge: Malaysia'),
    Emoji('🇲🇿', 'Flagge: Mosambik'),
    Emoji('🇳🇦', 'Flagge: Namibia'),
    Emoji('🇳🇨', 'Flagge: Neukaledonien'),
    Emoji('🇳🇪', 'Flagge: Niger'),
    Emoji('🇳🇫', 'Flagge: Norfolkinsel'),
    Emoji('🇳🇬', 'Flagge: Nigeria'),
    Emoji('🇳🇮', 'Flagge: Nicaragua'),
    Emoji('🇳🇱', 'Flagge: Niederlande'),
    Emoji('🇳🇴', 'Flagge: Norwegen'),
    Emoji('🇳🇵', 'Flagge: Nepal'),
    Emoji('🇳🇷', 'Flagge: Nauru'),
    Emoji('🇳🇺', 'Flagge: Niue'),
    Emoji('🇳🇿', 'Flagge: Neuseeland'),
    Emoji('🇴🇲', 'Flagge: Oman'),
    Emoji('🇵🇦', 'Flagge: Panama'),
    Emoji('🇵🇪', 'Flagge: Peru'),
    Emoji('🇵🇫', 'Flagge: Französisch-Polynesien'),
    Emoji('🇵🇬', 'Flagge: Papua-Neuguinea'),
    Emoji('🇵🇭', 'Flagge: Philippinen'),
    Emoji('🇵🇰', 'Flagge: Pakistan'),
    Emoji('🇵🇱', 'Flagge: Polen'),
    Emoji('🇵🇲', 'Flagge: Saint-Pierre und Miquelon'),
    Emoji('🇵🇳', 'Flagge: Pitcairninseln'),
    Emoji('🇵🇷', 'Flagge: Puerto Rico'),
    Emoji('🇵🇸', 'Flagge: Palästinensische Gebiete'),
    Emoji('🇵🇹', 'Flagge: Portugal'),
    Emoji('🇵🇼', 'Flagge: Palau'),
    Emoji('🇵🇾', 'Flagge: Paraguay'),
    Emoji('🇶🇦', 'Flagge: Katar'),
    Emoji('🇷🇪', 'Flagge: Réunion'),
    Emoji('🇷🇴', 'Flagge: Rumänien'),
    Emoji('🇷🇸', 'Flagge: Serbien'),
    Emoji('🇷🇺', 'Flagge: Russland'),
    Emoji('🇷🇼', 'Flagge: Ruanda'),
    Emoji('🇸🇦', 'Flagge: Saudi-Arabien'),
    Emoji('🇸🇧', 'Flagge: Salomonen'),
    Emoji('🇸🇨', 'Flagge: Seychellen'),
    Emoji('🇸🇩', 'Flagge: Sudan'),
    Emoji('🇸🇪', 'Flagge: Schweden'),
    Emoji('🇸🇬', 'Flagge: Singapur'),
    Emoji('🇸🇭', 'Flagge: St. Helena'),
    Emoji('🇸🇮', 'Flagge: Slowenien'),
    Emoji('🇸🇯', 'Flagge: Spitzbergen und Jan Mayen'),
    Emoji('🇸🇰', 'Flagge: Slowakei'),
    Emoji('🇸🇱', 'Flagge: Sierra Leone'),
    Emoji('🇸🇲', 'Flagge: San Marino'),
    Emoji('🇸🇳', 'Flagge: Senegal'),
    Emoji('🇸🇴', 'Flagge: Somalia'),
    Emoji('🇸🇷', 'Flagge: Suriname'),
    Emoji('🇸🇸', 'Flagge: Südsudan'),
    Emoji('🇸🇹', 'Flagge: São Tomé und Príncipe'),
    Emoji('🇸🇻', 'Flagge: El Salvador'),
    Emoji('🇸🇽', 'Flagge: Sint Maarten'),
    Emoji('🇸🇾', 'Flagge: Syrien'),
    Emoji('🇸🇿', 'Flagge: Swasiland'),
    Emoji('🇹🇦', 'Flagge: Tristan da Cunha'),
    Emoji('🇹🇨', 'Flagge: Turks- und Caicosinseln'),
    Emoji('🇹🇩', 'Flagge: Tschad'),
    Emoji('🇹🇫', 'Flagge: Französische Süd- und Antarktisgebiete'),
    Emoji('🇹🇬', 'Flagge: Togo'),
    Emoji('🇹🇭', 'Flagge: Thailand'),
    Emoji('🇹🇯', 'Flagge: Tadschikistan'),
    Emoji('🇹🇰', 'Flagge: Tokelau'),
    Emoji('🇹🇱', 'Flagge: Osttimor'),
    Emoji('🇹🇲', 'Flagge: Turkmenistan'),
    Emoji('🇹🇳', 'Flagge: Tunesien'),
    Emoji('🇹🇴', 'Flagge: Tonga'),
    Emoji('🇹🇷', 'Flagge: Türkei'),
    Emoji('🇹🇹', 'Flagge: Trinidad und Tobago'),
    Emoji('🇹🇻', 'Flagge: Tuvalu'),
    Emoji('🇹🇼', 'Flagge: Taiwan'),
    Emoji('🇹🇿', 'Flagge: Tansania'),
    Emoji('🇺🇦', 'Flagge: Ukraine'),
    Emoji('🇺🇬', 'Flagge: Uganda'),
    Emoji('🇺🇲', 'Flagge: Amerikanische Überseeinseln'),
    Emoji('🇺🇳', 'Flagge: Vereinte Nationen'),
    Emoji('🇺🇸', 'Flagge: Vereinigte Staaten'),
    Emoji('🇺🇾', 'Flagge: Uruguay'),
    Emoji('🇺🇿', 'Flagge: Usbekistan'),
    Emoji('🇻🇦', 'Flagge: Vatikanstadt'),
    Emoji('🇻🇨', 'Flagge: St. Vincent und die Grenadinen'),
    Emoji('🇻🇪', 'Flagge: Venezuela'),
    Emoji('🇻🇬', 'Flagge: Britische Jungferninseln'),
    Emoji('🇻🇮', 'Flagge: Amerikanische Jungferninseln'),
    Emoji('🇻🇳', 'Flagge: Vietnam'),
    Emoji('🇻🇺', 'Flagge: Vanuatu'),
    Emoji('🇼🇫', 'Flagge: Wallis und Futuna'),
    Emoji('🇼🇸', 'Flagge: Samoa'),
    Emoji('🇽🇰', 'Flagge: Kosovo'),
    Emoji('🇾🇪', 'Flagge: Jemen'),
    Emoji('🇾🇹', 'Flagge: Mayotte'),
    Emoji('🇿🇦', 'Flagge: Südafrika'),
    Emoji('🇿🇲', 'Flagge: Sambia'),
    Emoji('🇿🇼', 'Flagge: Simbabwe')
  ]),
];
